using System.Text;
using Microsoft.CodeAnalysis;

namespace IfItQuacks.Generator;

/// <summary>Conventions every generated file follows.</summary>
internal static class GeneratedCode
{
    public const string Namespace = "IfItQuacks.Generated";
    public const string Header = "// <auto-generated/>\n#nullable enable\n";
    public const string EditorBrowsableNever = "[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]";
    public const string InterceptorIndexPlaceholder = "__INDEX__";
    public const string AdaptersHintName = "IfItQuacks.Adapters.g.cs";
    public const string InterceptorsHintName = "IfItQuacks.Interceptors.g.cs";

    private const string HintNamePrefix = "IfItQuacks.";
    private const string HintNameSuffix = ".g.cs";

    // An anonymous type can't be named, so a value is cast to it through the type the compiler infers for an example of the same shape.
    public const string CastByExampleDeclaration = "private static T __CastByExample<T>(object value, global::System.Func<T> example) => (T)value;";

    public static string CastByExample(string value, string example) => $"__CastByExample({value}, static () => {example})";

    public static string HintName(string kind, INamedTypeSymbol type, string? member = null)
    {
        var typeName = type.ToDisplayString().Replace('.', '_').Replace('<', '_').Replace('>', '_').Replace(',', '_').Replace(' ', '_');
        return $"{HintNamePrefix}{kind}.{typeName}{(member is null ? "" : "." + member)}{HintNameSuffix}";
    }

    public static bool IsGeneratedFile(string path)
    {
        var fileName = path.Substring(path.LastIndexOfAny(['/', '\\']) + 1);
        return fileName.StartsWith(HintNamePrefix, StringComparison.Ordinal) && fileName.EndsWith(HintNameSuffix, StringComparison.Ordinal);
    }

    public static string ToIdentifier(string text)
    {
        var identifier = new StringBuilder(text.Length);
        foreach (var character in text)
            identifier.Append(char.IsLetterOrDigit(character) ? character : '_');
        return identifier.ToString();
    }
}
