<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />
  <Import Project="$(MSBuildThisFileDirectory)..\build\Consumer.props" />

  <PropertyGroup>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <CompilerGeneratedFilesOutputPath>Generated</CompilerGeneratedFilesOutputPath>
    <DefaultItemExcludes>$(DefaultItemExcludes);Generated/**</DefaultItemExcludes>
  </PropertyGroup>
</Project>
