namespace IfItQuacks.Generator;

internal static class EmbeddedSources
{
    public const string Attributes = """
        // <auto-generated/>
        #nullable enable
        namespace IfItQuacks
        {
            /// <summary>Marks a method whose interface parameters accept any type that structurally
            /// matches the interface, verified at compile time and dispatched via generated interceptors.</summary>
            [System.AttributeUsage(System.AttributeTargets.Method)]
            internal sealed class DuckTypedAttribute : System.Attribute
            {
            }

            /// <summary>Converts values to interfaces they structurally satisfy.</summary>
            internal static class Duck
            {
                /// <summary>Returns <paramref name="value"/> as <typeparamref name="TShape"/>. The call is verified at compile time and
                /// replaced by a generated adapter, or by a plain cast if the value already implements the interface.</summary>
                public static TShape As<TShape>(object value) where TShape : class
                {
                    return value as TShape ?? throw new DuckTypeMismatchException(value?.GetType() ?? typeof(object), typeof(TShape));
                }

                /// <summary>Returns the original instance behind a generated adapter, or <paramref name="value"/> itself
                /// if it is not an adapter (e.g. because its type already implements the interface).</summary>
                public static object? Unwrap(object? value) => value is IDuckAdapter adapter ? adapter.Value : value;
            }

            /// <summary>Implemented by every generated adapter to expose the instance it forwards to.</summary>
            [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
            internal interface IDuckAdapter
            {
                object? Value { get; }
            }

            /// <summary>Thrown when a call that couldn't be verified at compile time (e.g. from generic code)
            /// receives a value that doesn't implement the interface at runtime. Verified mismatches are build errors instead.</summary>
            internal sealed class DuckTypeMismatchException : System.Exception
            {
                public DuckTypeMismatchException(System.Type actualType, System.Type shapeType)
                    : base($"Type '{actualType}' does not implement '{shapeType}' and could not be duck-typed at compile time.")
                {
                }
            }
        }
        """;

    public const string InterceptsLocationAttributePolyfill = """
        // <auto-generated/>
        #pragma warning disable CS9113 // positional parameters are read by the compiler itself, not by this type
        namespace System.Runtime.CompilerServices
        {
            [System.AttributeUsage(System.AttributeTargets.Method, AllowMultiple = true)]
            file sealed class InterceptsLocationAttribute(int version, string data) : System.Attribute
            {
            }
        }
        #pragma warning restore CS9113
        """;
}
