using System.Collections.Immutable;
using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

#pragma warning disable RSEXPERIMENTAL002 // InterceptableLocation API is experimental

namespace IfItQuacks.Generator;

/// <summary>
/// Generates adapters and interceptors that let <c>[DuckTyped]</c> methods accept any type structurally matching a <c>[DuckShape]</c> interface.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class IfItQuacksGenerator : IIncrementalGenerator
{
    private const string DuckTypedAttributeName = "IfItQuacks.DuckTypedAttribute";
    private const string DuckShapeAttributeName = "IfItQuacks.DuckShapeAttribute";
    private const string DuckTypeName = "IfItQuacks.Duck";
    private const string DuckAsMethodName = "As";
    private const string GeneratedNamespace = "IfItQuacks.Generated";
    private const string InterceptorIndexPlaceholder = "__INDEX__";
    private const string EditorBrowsableNever = "[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]";
    private const string Header = "// <auto-generated/>\n#nullable enable\n";

    internal const string CallSitesTrackingName = "IfItQuacks.CallSites";

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource("IfItQuacksAttributes.g.cs", SourceText.From(EmbeddedSources.Attributes, Encoding.UTF8)));

        var duckTypedMethods = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                DuckTypedAttributeName,
                predicate: static (node, _) => node is MethodDeclarationSyntax,
                transform: static (ctx, _) => AnalyzeDuckTypedMethod(ctx));

        context.RegisterSourceOutput(duckTypedMethods, static (spc, method) => EmitDuckTypedMethod(spc, method));

        var duckTypedNames = duckTypedMethods
            .Select(static (method, _) => method.Name)
            .Collect()
            .Select(static (names, _) => new EquatableArray<string>(names.Distinct(StringComparer.Ordinal).OrderBy(n => n, StringComparer.Ordinal).ToImmutableArray()));

        var callSites = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is InvocationExpressionSyntax { ArgumentList.Arguments.Count: > 0 } invocation &&
                                               GetInvokedName(invocation) is not null,
                transform: static (ctx, _) => (InvocationExpressionSyntax)ctx.Node)
            .Combine(duckTypedNames)
            .Where(static pair => GetInvokedName(pair.Left) is { } name && (name == DuckAsMethodName || pair.Right.Contains(name)))
            .Select(static (pair, _) => pair.Left)
            .Combine(context.CompilationProvider)
            .Select(static (pair, ct) => AnalyzeCallSite(pair.Left, pair.Right, ct))
            .WithTrackingName(CallSitesTrackingName);

        context.RegisterSourceOutput(callSites.Collect(), static (spc, sites) => EmitCallSites(spc, sites));
    }

    private static DuckTypedMethodOutput AnalyzeDuckTypedMethod(GeneratorAttributeSyntaxContext ctx)
    {
        var method = (IMethodSymbol)ctx.TargetSymbol;
        var diagnostics = ImmutableArray.CreateBuilder<Diagnostic>();
        var isValid = ValidateDuckTypedMethod(method, ctx.TargetNode.GetLocation(), diagnostics);

        var fallback = isValid && !method.IsGenericMethod ? CreateFallbackOverload(method) : null;
        return new DuckTypedMethodOutput(method.Name, fallback, new EquatableArray<Diagnostic>(diagnostics.ToImmutable()));
    }

    private static bool ValidateDuckTypedMethod(IMethodSymbol method, Location location, ImmutableArray<Diagnostic>.Builder? diagnostics)
    {
        if (method.ContainingType.DeclaringSyntaxReferences
                .Select(r => r.GetSyntax())
                .OfType<TypeDeclarationSyntax>()
                .Any(t => !t.Modifiers.Any(SyntaxKind.PartialKeyword)))
        {
            diagnostics?.Add(Diagnostic.Create(Diagnostics.ContainingTypeNotPartial, location,
                method.Name, method.ContainingType.Name));
        }

        var unsupportedReason = method switch
        {
            { IsExtensionMethod: true } => "it is an extension method",
            { IsStatic: false, ContainingType.IsValueType: true } => "it is an instance method of a struct",
            { DeclaredAccessibility: Accessibility.Private or Accessibility.Protected or Accessibility.ProtectedAndInternal } =>
                "it is not accessible from the generated interceptors (use public or internal)",
            _ when IsInGenericType(method.ContainingType) => "its containing type is generic",
            _ => null,
        };
        if (unsupportedReason is not null)
        {
            diagnostics?.Add(Diagnostic.Create(Diagnostics.UnsupportedSignature, location, method.Name, unsupportedReason));
            return false;
        }

        var duckParameters = GetDuckParameters(method);
        if (duckParameters.IsEmpty)
        {
            diagnostics?.Add(Diagnostic.Create(Diagnostics.ParameterNotShape, location, method.Name));
            return false;
        }

        var byReference = duckParameters.FirstOrDefault(p => p.RefKind != RefKind.None);
        if (byReference is not null)
        {
            diagnostics?.Add(Diagnostic.Create(Diagnostics.UnsupportedSignature, location, method.Name,
                $"its [DuckShape] parameter '{byReference.Name}' is declared '{Utilities.RefKindPrefix(byReference.RefKind).Trim()}'"));
            return false;
        }

        var unusedTypeParameter = method.TypeParameters.FirstOrDefault(tp => !duckParameters.Any(p => ContainsTypeParameter(p.Type, tp)));
        if (unusedTypeParameter is not null)
        {
            diagnostics?.Add(Diagnostic.Create(Diagnostics.UnsupportedSignature, location, method.Name,
                $"its type parameter '{unusedTypeParameter.Name}' is not used by a [DuckShape] parameter"));
            return false;
        }

        if (method.ContainingType.GetMembers(method.Name).OfType<IMethodSymbol>().Count(IsDuckTyped) > 1)
        {
            diagnostics?.Add(Diagnostic.Create(Diagnostics.UnsupportedSignature, location, method.Name,
                "it is overloaded (only one [DuckTyped] method per name is supported)"));
            return false;
        }

        return true;
    }

    private static CallSiteOutput? AnalyzeCallSite(InvocationExpressionSyntax invocation, Compilation compilation, CancellationToken ct)
    {
        if (!compilation.ContainsSyntaxTree(invocation.SyntaxTree))
            return null;

        var semanticModel = compilation.GetSemanticModel(invocation.SyntaxTree);
        var symbolInfo = semanticModel.GetSymbolInfo(invocation, ct);
        var candidates = symbolInfo.Symbol is IMethodSymbol s
            ? [s]
            : symbolInfo.CandidateSymbols.OfType<IMethodSymbol>().ToImmutableArray();

        var duckAsCall = candidates.FirstOrDefault(c => IsDuckAs(c, compilation));
        if (duckAsCall is not null)
            return AnalyzeDuckAsCall(semanticModel, invocation, duckAsCall, ct);

        var duckMethod = candidates
            .Select(c => c.OriginalDefinition)
            .FirstOrDefault(c => c.DeclaringSyntaxReferences.Length > 0 && IsDuckTyped(c));
        if (duckMethod is null || !ValidateDuckTypedMethod(duckMethod, Location.None, diagnostics: null))
            return null;

        var arguments = MapArguments(invocation.ArgumentList, duckMethod);
        if (arguments is null)
            return null;

        var duckArguments = new List<(IParameterSymbol Parameter, ExpressionSyntax Expression, INamedTypeSymbol ConcreteType)>();
        foreach (var parameter in GetDuckParameters(duckMethod))
        {
            if (!arguments.TryGetValue(parameter.Ordinal, out var expression) ||
                semanticModel.GetTypeInfo(expression, ct).Type is not INamedTypeSymbol concreteType ||
                concreteType.TypeKind == TypeKind.Error ||
                (duckMethod.IsGenericMethod && ContainsAnyTypeParameter(concreteType)))
                return null;

            duckArguments.Add((parameter, expression, concreteType));
        }

        var diagnostics = ImmutableArray.CreateBuilder<Diagnostic>();
        var targetMethod = duckMethod;
        if (duckMethod.IsGenericMethod)
        {
            foreach (var (parameter, expression, concreteType) in duckArguments)
            {
                if (FindUnsupportedMemberDiagnostic(expression, (INamedTypeSymbol)parameter.Type) is { } unsupported)
                    diagnostics.Add(unsupported);
                else if (concreteType.IsAnonymousType)
                    diagnostics.Add(Diagnostic.Create(Diagnostics.ShapeMismatch, expression.GetLocation(), concreteType.ToDisplayString(),
                        parameter.Type.ToDisplayString(), "anonymous types are not supported by generic [DuckTyped] methods"));
            }
            if (diagnostics.Count > 0)
                return DiagnosticsOnly(diagnostics);

            var constructed = TypeArgumentInference.TryConstruct(duckMethod, duckArguments.Select(a => (a.Parameter, a.ConcreteType)));
            if (constructed is null)
            {
                var failing = duckArguments.FirstOrDefault(a => ShapeMatcher.FindMismatch((INamedTypeSymbol)a.Parameter.Type, a.ConcreteType, compilation) is not null);
                if (failing.Parameter is null)
                    failing = duckArguments[0];
                diagnostics.Add(Diagnostic.Create(Diagnostics.ShapeMismatch, failing.Expression.GetLocation(),
                    failing.ConcreteType.ToDisplayString(), failing.Parameter.Type.ToDisplayString(),
                    ShapeMatcher.FindMismatch((INamedTypeSymbol)failing.Parameter.Type, failing.ConcreteType, compilation)
                    ?? $"type arguments for '{duckMethod.Name}' could not be inferred"));
                return DiagnosticsOnly(diagnostics);
            }
            targetMethod = constructed;
        }

        var adapters = ImmutableArray.CreateBuilder<GeneratedFile>();
        var resolved = new Dictionary<int, (INamedTypeSymbol ConcreteType, string? AdapterName)>();
        foreach (var (parameter, expression, concreteType) in duckArguments)
        {
            var shape = (INamedTypeSymbol)targetMethod.Parameters[parameter.Ordinal].Type;
            if (VerifyArgument(expression, shape, concreteType, compilation, out var implementsDirectly) is { } diagnostic)
            {
                diagnostics.Add(diagnostic);
                continue;
            }

            var adapter = implementsDirectly ? null : CreateAdapter(shape, concreteType, compilation);
            if (adapter is not null)
                adapters.Add(adapter);
            resolved[parameter.Ordinal] = (concreteType, adapter?.Name);
        }

        if (diagnostics.Count > 0)
            return DiagnosticsOnly(diagnostics);

        if (duckMethod.IsGenericMethod)
        {
            return adapters.Count == 0
                ? null
                : new CallSiteOutput(null, new EquatableArray<GeneratedFile>(adapters.ToImmutable()),
                    CreateDuckOverload(duckMethod, targetMethod, resolved), default);
        }

        var location = semanticModel.GetInterceptableLocation(invocation, ct);
        if (location is null)
            return null;

        return new CallSiteOutput(CreateInterceptor(location, duckMethod, resolved),
            new EquatableArray<GeneratedFile>(adapters.ToImmutable()), null, default);
    }

    private static CallSiteOutput? AnalyzeDuckAsCall(SemanticModel semanticModel, InvocationExpressionSyntax invocation,
        IMethodSymbol duckAsCall, CancellationToken ct)
    {
        var typeArgument = duckAsCall.TypeArguments[0];
        if (typeArgument is not INamedTypeSymbol { TypeKind: TypeKind.Interface } shape || !IsDuckShape(shape))
        {
            return DiagnosticsOnly([Diagnostic.Create(Diagnostics.ConversionTargetNotShape, invocation.GetLocation(),
                typeArgument.ToDisplayString())]);
        }

        if (invocation.ArgumentList.Arguments.Count != 1 || ContainsAnyTypeParameter(shape))
            return null;

        var argExpr = invocation.ArgumentList.Arguments[0].Expression;
        if (semanticModel.GetTypeInfo(argExpr, ct).Type is not INamedTypeSymbol concreteType ||
            concreteType.TypeKind == TypeKind.Error || ContainsAnyTypeParameter(concreteType))
            return null;

        if (VerifyArgument(argExpr, shape, concreteType, semanticModel.Compilation, out var implementsDirectly) is { } diagnostic)
            return DiagnosticsOnly([diagnostic]);

        var location = semanticModel.GetInterceptableLocation(invocation, ct);
        if (location is null)
            return null;

        var shapeTypeName = shape.ToDisplayString();
        var adapter = implementsDirectly ? null : CreateAdapter(shape, concreteType, semanticModel.Compilation);
        var argument = concreteType.IsAnonymousType ? "value" : $"({concreteType.ToDisplayString()})value";
        var result = adapter is null ? "value" : $"new global::{GeneratedNamespace}.{adapter.Name}({argument})";

        var interceptor =
            $"        {location.GetInterceptsLocationAttributeSyntax()}\n" +
            $"        public static global::{shapeTypeName} Interceptor_{InterceptorIndexPlaceholder}(object value) => (global::{shapeTypeName})({result});\n";

        return new CallSiteOutput(interceptor,
            adapter is null ? default : new EquatableArray<GeneratedFile>([adapter]), null, default);
    }

    private static Dictionary<int, ExpressionSyntax>? MapArguments(ArgumentListSyntax argumentList, IMethodSymbol method)
    {
        var arguments = new Dictionary<int, ExpressionSyntax>();
        for (var i = 0; i < argumentList.Arguments.Count; i++)
        {
            var argument = argumentList.Arguments[i];
            IParameterSymbol? parameter;
            if (argument.NameColon is { } nameColon)
                parameter = method.Parameters.FirstOrDefault(p => p.Name == nameColon.Name.Identifier.ValueText);
            else if (i < method.Parameters.Length)
                parameter = method.Parameters[i];
            else
                parameter = method.Parameters.LastOrDefault(p => p.IsParams);

            if (parameter is null)
                return null;

            arguments[parameter.Ordinal] = argument.Expression;
        }
        return arguments;
    }

    private static Diagnostic? VerifyArgument(ExpressionSyntax argExpr, INamedTypeSymbol shape, INamedTypeSymbol concreteType,
        Compilation compilation, out bool implementsDirectly)
    {
        implementsDirectly = false;

        if (FindUnsupportedMemberDiagnostic(argExpr, shape) is { } unsupported)
            return unsupported;

        var mismatch = ShapeMatcher.FindMismatch(shape, concreteType, compilation) ??
                       (concreteType.IsAnonymousType && AdapterEmitter.FindUnnameableProperty(concreteType) is { } property
                           ? $"property '{property}' has a type that contains an anonymous type"
                           : null);
        if (mismatch is not null)
        {
            return Diagnostic.Create(Diagnostics.ShapeMismatch, argExpr.GetLocation(),
                concreteType.ToDisplayString(), shape.ToDisplayString(), mismatch);
        }

        implementsDirectly = concreteType.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i, shape));

        var unsupportedStructKind = GetUnsupportedStructKind(concreteType, implementsDirectly);
        return unsupportedStructKind is null
            ? null
            : Diagnostic.Create(Diagnostics.UnsupportedStructArgument, argExpr.GetLocation(),
                concreteType.ToDisplayString(), shape.ToDisplayString(), unsupportedStructKind);
    }

    private static Diagnostic? FindUnsupportedMemberDiagnostic(ExpressionSyntax argExpr, INamedTypeSymbol shape) =>
        ShapeMatcher.FindUnsupportedMember(shape) is { } member
            ? Diagnostic.Create(Diagnostics.UnsupportedShapeMember, argExpr.GetLocation(), shape.ToDisplayString(),
                member.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat))
            : null;

    private static CallSiteOutput DiagnosticsOnly(IEnumerable<Diagnostic> diagnostics) =>
        new(null, default, null, new EquatableArray<Diagnostic>(diagnostics.ToImmutableArray()));

    private static GeneratedFile CreateAdapter(INamedTypeSymbol shape, INamedTypeSymbol concreteType, Compilation compilation)
    {
        var name = AdapterEmitter.GetAdapterName(shape, concreteType);
        return new GeneratedFile(name, AdapterEmitter.Emit(shape, concreteType, name, compilation));
    }

    private static ImmutableArray<IParameterSymbol> GetDuckParameters(IMethodSymbol method) =>
        method.Parameters
            .Where(p => p.Type is INamedTypeSymbol { TypeKind: TypeKind.Interface } type && IsDuckShape(type))
            .ToImmutableArray();

    private static bool IsDuckTyped(IMethodSymbol method) =>
        method.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == DuckTypedAttributeName);

    private static bool IsDuckShape(INamedTypeSymbol type) =>
        type.OriginalDefinition.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == DuckShapeAttributeName);

    private static bool IsDuckAs(IMethodSymbol method, Compilation compilation) =>
        method.Name == DuckAsMethodName &&
        method.ContainingType.ToDisplayString() == DuckTypeName &&
        SymbolEqualityComparer.Default.Equals(method.ContainingAssembly, compilation.Assembly);

    private static bool IsInGenericType(INamedTypeSymbol type)
    {
        for (var t = type; t is not null; t = t.ContainingType)
            if (t.IsGenericType)
                return true;
        return false;
    }

    // A struct implementing the shape is boxed by the compiler itself, so only adapter-wrapped mutable structs would silently lose mutations.
    private static string? GetUnsupportedStructKind(INamedTypeSymbol type, bool implementsDirectly)
    {
        if (type.IsRefLikeType)
            return "ref structs cannot be converted to an interface";

        if (type.IsValueType && !type.IsReadOnly && !implementsDirectly)
            return "mutable structs are copied into an adapter, so mutations made through the shape would be lost";

        return null;
    }

    private static string? GetInvokedName(InvocationExpressionSyntax invocation) => invocation.Expression switch
    {
        SimpleNameSyntax name => name.Identifier.Text,
        MemberAccessExpressionSyntax member => member.Name.Identifier.Text,
        _ => null,
    };

    private static void EmitDuckTypedMethod(SourceProductionContext spc, DuckTypedMethodOutput method)
    {
        foreach (var diagnostic in method.Diagnostics)
            spc.ReportDiagnostic(diagnostic);

        if (method.Fallback is not null)
            spc.AddSource(method.Fallback.Name, SourceText.From(method.Fallback.Source, Encoding.UTF8));
    }

    private static void EmitCallSites(SourceProductionContext spc, ImmutableArray<CallSiteOutput?> sites)
    {
        var adapters = new SortedDictionary<string, string>(StringComparer.Ordinal);
        var overloadFiles = new SortedDictionary<string, (OverloadMember Template, SortedSet<string> Members)>(StringComparer.Ordinal);
        var interceptors = new StringBuilder();
        var interceptorCount = 0;

        foreach (var site in sites.OfType<CallSiteOutput>())
        {
            foreach (var diagnostic in site.Diagnostics)
                spc.ReportDiagnostic(diagnostic);

            foreach (var adapter in site.Adapters)
                adapters[adapter.Name] = adapter.Source;

            if (site.Overload is { } overload)
            {
                if (!overloadFiles.TryGetValue(overload.FileName, out var file))
                    overloadFiles[overload.FileName] = file = (overload, new SortedSet<string>(StringComparer.Ordinal));
                file.Members.Add(overload.Member);
            }

            if (site.Interceptor is not null)
            {
                interceptorCount++;
                interceptors.AppendLine();
                interceptors.Append(site.Interceptor.Replace(InterceptorIndexPlaceholder, interceptorCount.ToString(CultureInfo.InvariantCulture)));
            }
        }

        foreach (var (template, members) in overloadFiles.Values)
        {
            var indent = template.Prefix.Substring(template.Prefix.LastIndexOf('\n') + 1);
            var source = template.Prefix + string.Join("\n" + indent, members) + template.Suffix;
            spc.AddSource(template.FileName, SourceText.From(source, Encoding.UTF8));
        }

        if (interceptorCount > 0)
        {
            var sb = new StringBuilder(Header);
            sb.AppendLine(EmbeddedSources.InterceptsLocationAttributePolyfill);
            sb.AppendLine("namespace " + GeneratedNamespace);
            sb.AppendLine("{");
            sb.AppendLine("    file static class IfItQuacksInterceptors");
            sb.AppendLine("    {");
            sb.Append(interceptors);
            sb.AppendLine("    }");
            sb.AppendLine("}");
            spc.AddSource("IfItQuacks.Interceptors.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        if (adapters.Count > 0)
        {
            var sb = new StringBuilder(Header);
            sb.AppendLine("namespace " + GeneratedNamespace);
            sb.AppendLine("{");
            foreach (var adapter in adapters.Values)
                sb.Append(adapter);
            sb.AppendLine("}");
            spc.AddSource("IfItQuacks.Adapters.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }
    }

    private static GeneratedFile CreateFallbackOverload(IMethodSymbol method)
    {
        var duckParameters = GetDuckParameters(method);
        var typeParameterNames = duckParameters.ToDictionary(p => p.Ordinal, FallbackTypeParameterName);

        var parameters = string.Join(", ", method.Parameters.Select(p =>
            Utilities.Parameter(p, typeParameterNames.TryGetValue(p.Ordinal, out var name) ? name : p.Type.ToDisplayString()) + Utilities.DefaultValue(p)));
        var first = duckParameters[0];

        var methodSource = $$"""
            {{EditorBrowsableNever}}
            {{Utilities.AccessibilityKeyword(method.DeclaredAccessibility)}} {{(method.IsStatic ? "static " : "")}}{{method.ReturnType.ToDisplayString()}} {{method.Name}}<{{string.Join(", ", typeParameterNames.Values)}}>({{parameters}})
            {
                throw new global::IfItQuacks.DuckShapeMismatchException(typeof({{typeParameterNames[first.Ordinal]}}), typeof({{first.Type.ToDisplayString()}}));
            }
            """;

        return new GeneratedFile(
            $"IfItQuacks.Fallback.{SanitizeHintName(method.ContainingType.ToDisplayString())}.{method.Name}.g.cs",
            Header + TypeWrapper.WrapInContainingScope(method.ContainingType, methodSource));
    }

    // Interceptors must keep the intercepted signature, so a generic fallback can't return the per-call inferred type; concrete overloads can.
    private static OverloadMember CreateDuckOverload(IMethodSymbol method, IMethodSymbol constructed,
        Dictionary<int, (INamedTypeSymbol ConcreteType, string? AdapterName)> duckArguments)
    {
        var accessibility = method.DeclaredAccessibility is Accessibility.Public or Accessibility.Protected or Accessibility.ProtectedOrInternal &&
                            !duckArguments.Values.All(a => IsPubliclyVisible(a.ConcreteType))
            ? "internal"
            : Utilities.AccessibilityKeyword(method.DeclaredAccessibility);

        var parameters = string.Join(", ", constructed.Parameters.Select(p =>
            Utilities.Parameter(p, duckArguments.TryGetValue(p.Ordinal, out var duck) ? duck.ConcreteType.ToDisplayString() : p.Type.ToDisplayString()) +
            Utilities.DefaultValue(p)));

        var arguments = string.Join(", ", constructed.Parameters.Select(p =>
            duckArguments.TryGetValue(p.Ordinal, out var duck) && duck.AdapterName is not null
                ? $"new global::{GeneratedNamespace}.{duck.AdapterName}({Utilities.Identifier(p.Name)})"
                : Utilities.Argument(p)));

        var typeArguments = string.Join(", ", constructed.TypeArguments.Select(t => t.ToDisplayString()));
        var member =
            $"{EditorBrowsableNever} {accessibility} {(method.IsStatic ? "static " : "")}{constructed.ReturnType.ToDisplayString()} {method.Name}({parameters}) => " +
            $"{method.Name}<{typeArguments}>({arguments});";

        var (prefix, suffix) = TypeWrapper.WrapTemplate(method.ContainingType);
        return new OverloadMember(
            $"IfItQuacks.Overloads.{SanitizeHintName(method.ContainingType.ToDisplayString())}.{method.Name}.g.cs",
            Header + prefix, suffix, member);
    }

    private static string CreateInterceptor(InterceptableLocation location, IMethodSymbol method,
        Dictionary<int, (INamedTypeSymbol ConcreteType, string? AdapterName)> duckArguments)
    {
        // Anonymous types can't be named in the signature, so the interceptor stays generic like the fallback it replaces.
        var isGeneric = duckArguments.Values.Any(d => d.ConcreteType.IsAnonymousType);
        var parameters = method.Parameters.Select(p =>
        {
            if (!duckArguments.TryGetValue(p.Ordinal, out var duck))
                return Utilities.Parameter(p, p.Type.ToDisplayString());
            return Utilities.Parameter(p, isGeneric ? FallbackTypeParameterName(p) : duck.ConcreteType.ToDisplayString());
        });
        if (!method.IsStatic)
            parameters = parameters.Prepend($"this global::{method.ContainingType.ToDisplayString()} @this");

        // Casting to the shape interface makes overload resolution pick the real method instead of the generated generic fallback.
        var arguments = method.Parameters.Select(p =>
        {
            if (!duckArguments.TryGetValue(p.Ordinal, out var duck))
                return Utilities.Argument(p);

            var name = Utilities.Identifier(p.Name);
            if (isGeneric)
                name = duck.ConcreteType.IsAnonymousType ? $"(object){name}!" : $"({duck.ConcreteType.ToDisplayString()})(object){name}!";
            var value = duck.AdapterName is null ? name : $"new global::{GeneratedNamespace}.{duck.AdapterName}({name})";
            return $"(global::{p.Type.ToDisplayString()})({value})";
        });
        var typeParameters = isGeneric ? $"<{string.Join(", ", GetDuckParameters(method).Select(FallbackTypeParameterName))}>" : "";

        var receiver = method.IsStatic ? $"global::{method.ContainingType.ToDisplayString()}" : "@this";
        var call = $"{receiver}.{method.Name}({string.Join(", ", arguments)});";

        var sb = new StringBuilder();
        sb.AppendLine("        " + location.GetInterceptsLocationAttributeSyntax());
        sb.AppendLine($"        public static {method.ReturnType.ToDisplayString()} Interceptor_{InterceptorIndexPlaceholder}{typeParameters}({string.Join(", ", parameters)})");
        sb.AppendLine("        {");
        sb.AppendLine(method.ReturnsVoid ? $"            {call}" : $"            return {call}");
        sb.AppendLine("        }");
        return sb.ToString();
    }

    private static string FallbackTypeParameterName(IParameterSymbol parameter) => $"TDuck{parameter.Ordinal}";

    private static string SanitizeHintName(string name) => name.Replace('.', '_').Replace('<', '_').Replace('>', '_').Replace(',', '_').Replace(' ', '_');

    private static bool IsPubliclyVisible(ITypeSymbol type) => type switch
    {
        INamedTypeSymbol named => IsDeclaredPublic(named) && named.TypeArguments.All(IsPubliclyVisible),
        IArrayTypeSymbol array => IsPubliclyVisible(array.ElementType),
        _ => true,
    };

    private static bool IsDeclaredPublic(INamedTypeSymbol type)
    {
        for (var t = type; t is not null; t = t.ContainingType)
            if (t.DeclaredAccessibility != Accessibility.Public)
                return false;
        return true;
    }

    private static bool ContainsTypeParameter(ITypeSymbol type, ITypeParameterSymbol typeParameter) => type switch
    {
        ITypeParameterSymbol tp => SymbolEqualityComparer.Default.Equals(tp, typeParameter),
        INamedTypeSymbol named => named.TypeArguments.Any(t => ContainsTypeParameter(t, typeParameter)),
        IArrayTypeSymbol array => ContainsTypeParameter(array.ElementType, typeParameter),
        _ => false,
    };

    private static bool ContainsAnyTypeParameter(ITypeSymbol type) => type switch
    {
        ITypeParameterSymbol => true,
        INamedTypeSymbol named => named.TypeArguments.Any(ContainsAnyTypeParameter),
        IArrayTypeSymbol array => ContainsAnyTypeParameter(array.ElementType),
        _ => false,
    };
}
