using System.Collections.Immutable;
using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

#pragma warning disable RSEXPERIMENTAL002 // InterceptableLocation API is experimental

namespace IfItQuacks.Generator;

/// <summary>
/// Generates adapters and interceptors that let <c>[DuckTyped]</c> methods accept any type structurally matching their interface parameters.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class IfItQuacksGenerator : IIncrementalGenerator
{
    private const string DuckTypedAttributeName = "IfItQuacks.DuckTypedAttribute";
    private const string DuckTypeName = "IfItQuacks.Duck";
    private const string DuckAsMethodName = "As";
    private const string GeneratedNamespace = "IfItQuacks.Generated";
    private const string InterceptorIndexPlaceholder = "__INDEX__";
    private const string EditorBrowsableNever = "[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]";
    private const string Header = "// <auto-generated/>\n#nullable enable\n";

    internal const string CallSitesTrackingName = "IfItQuacks.CallSites";
    internal const string MethodGroupsTrackingName = "IfItQuacks.MethodGroups";

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource("IfItQuacksAttributes.g.cs", SourceText.From(EmbeddedSources.Attributes, Encoding.UTF8)));

        var duckTypedMethods = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                DuckTypedAttributeName,
                predicate: static (node, _) => node is MethodDeclarationSyntax,
                transform: static (ctx, _) => AnalyzeDuckTypedMethod(ctx));

        context.RegisterSourceOutput(duckTypedMethods, static (spc, method) => EmitDuckTypedMethod(spc, method));

        var duckTypedNames = duckTypedMethods
            .Select(static (method, _) => method.Name)
            .Collect()
            .Select(static (names, _) => new EquatableArray<string>(names.Distinct(StringComparer.Ordinal).OrderBy(n => n, StringComparer.Ordinal).ToImmutableArray()));

        var callSites = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is InvocationExpressionSyntax { ArgumentList.Arguments.Count: > 0 } invocation &&
                                               GetInvokedName(invocation) is not null,
                transform: static (ctx, _) => (InvocationExpressionSyntax)ctx.Node)
            .Combine(duckTypedNames)
            .Where(static pair => GetInvokedName(pair.Left) is { } name && (name == DuckAsMethodName || pair.Right.Contains(name)))
            .Select(static (pair, _) => pair.Left)
            .Combine(context.CompilationProvider)
            .Select(static (pair, ct) => AnalyzeCallSite(pair.Left, pair.Right, ct))
            .WithTrackingName(CallSitesTrackingName);

        // A method group can't be intercepted, so a concrete overload is generated for the delegate it converts to.
        var methodGroups = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => AsMethodGroup(node) is not null,
                transform: static (ctx, _) => AsMethodGroup(ctx.Node)!)
            .Combine(duckTypedNames)
            .Where(static pair => pair.Right.Contains(GetMethodGroupName(pair.Left)))
            .Select(static (pair, _) => pair.Left)
            .Combine(context.CompilationProvider)
            .Select(static (pair, ct) => AnalyzeMethodGroup(pair.Left, pair.Right, ct))
            .WithTrackingName(MethodGroupsTrackingName);

        context.RegisterSourceOutput(callSites.Collect().Combine(methodGroups.Collect()),
            static (spc, sites) => EmitCallSites(spc, [.. sites.Left, .. sites.Right]));
    }

    private static DuckTypedMethodOutput AnalyzeDuckTypedMethod(GeneratorAttributeSyntaxContext ctx)
    {
        var method = (IMethodSymbol)ctx.TargetSymbol;
        var diagnostics = ImmutableArray.CreateBuilder<Diagnostic>();
        var isValid = ValidateDuckTypedMethod(method, ctx.TargetNode.GetLocation(), diagnostics);

        var fallback = isValid && !method.IsGenericMethod ? CreateFallbackOverload(method) : null;
        return new DuckTypedMethodOutput(method.Name, fallback, new EquatableArray<Diagnostic>(diagnostics.ToImmutable()));
    }

    private static bool ValidateDuckTypedMethod(IMethodSymbol method, Location location, ImmutableArray<Diagnostic>.Builder? diagnostics)
    {
        if (method.ContainingType.DeclaringSyntaxReferences
                .Select(r => r.GetSyntax())
                .OfType<TypeDeclarationSyntax>()
                .Any(t => !t.Modifiers.Any(SyntaxKind.PartialKeyword)))
        {
            diagnostics?.Add(Diagnostic.Create(Diagnostics.ContainingTypeNotPartial, location,
                method.Name, method.ContainingType.Name));
        }

        var unsupportedReason = method switch
        {
            { IsExtensionMethod: true } => "it is an extension method",
            _ when IsInGenericType(method.ContainingType) => "its containing type is generic",
            _ when method.ContainingType.TypeKind == TypeKind.Interface => "its containing type is an interface",
            // A file-local type can't be extended by a partial declaration in the generated file.
            _ when IsInFileLocalType(method.ContainingType) => "its containing type is file-local",
            _ => null,
        };
        if (unsupportedReason is not null)
        {
            diagnostics?.Add(Diagnostic.Create(Diagnostics.UnsupportedSignature, location, method.Name, unsupportedReason));
            return false;
        }

        var duckParameters = GetDuckParameters(method);
        var constraintTypeParameters = GetConstraintTypeParameters(method);
        if (!constraintTypeParameters.IsEmpty)
            return ValidateConstraintMethod(method, duckParameters, constraintTypeParameters, location, diagnostics);

        if (duckParameters.IsEmpty)
        {
            diagnostics?.Add(Diagnostic.Create(Diagnostics.ParameterNotShape, location, method.Name));
            return false;
        }

        var unusedTypeParameter = method.TypeParameters.FirstOrDefault(tp => !duckParameters.Any(p => ContainsTypeParameter(p.Type, tp)));
        if (unusedTypeParameter is not null)
        {
            diagnostics?.Add(Diagnostic.Create(Diagnostics.UnsupportedSignature, location, method.Name,
                $"its type parameter '{unusedTypeParameter.Name}' is not used by an interface parameter"));
            return false;
        }

        if (method.ContainingType.GetMembers(method.Name).OfType<IMethodSymbol>().Count(IsDuckTyped) > 1)
        {
            diagnostics?.Add(Diagnostic.Create(Diagnostics.UnsupportedSignature, location, method.Name,
                "it is overloaded (only one [DuckTyped] method per name is supported)"));
            return false;
        }

        return true;
    }

    // A duck-typed constraint, e.g. 'where T : IAddable<T>', lets static abstract members and operators be matched structurally.
    private static ImmutableArray<ITypeParameterSymbol> GetConstraintTypeParameters(IMethodSymbol method) =>
        method.TypeParameters
            .Where(tp => tp.ConstraintTypes.Length == 1 &&
                         tp.ConstraintTypes[0] is INamedTypeSymbol { TypeKind: TypeKind.Interface } &&
                         method.Parameters.Any(p => p is { RefKind: RefKind.None } && SymbolEqualityComparer.Default.Equals(p.Type, tp)))
            .ToImmutableArray();

    private static bool ValidateConstraintMethod(IMethodSymbol method, ImmutableArray<IParameterSymbol> duckParameters,
        ImmutableArray<ITypeParameterSymbol> constraintTypeParameters, Location location, ImmutableArray<Diagnostic>.Builder? diagnostics)
    {
        string? reason = null;
        if (!duckParameters.IsEmpty)
            reason = "it mixes interface parameters with duck-typed constraints";
        else if (method.TypeParameters.Length != constraintTypeParameters.Length)
            reason = "not all of its type parameters have a single interface constraint used by a parameter";

        if (reason is null)
            return true;

        diagnostics?.Add(Diagnostic.Create(Diagnostics.UnsupportedSignature, location, method.Name, reason));
        return false;
    }

    private static CallSiteOutput? AnalyzeCallSite(InvocationExpressionSyntax invocation, Compilation compilation, CancellationToken ct)
    {
        if (!compilation.ContainsSyntaxTree(invocation.SyntaxTree))
            return null;

        var semanticModel = compilation.GetSemanticModel(invocation.SyntaxTree);
        var symbolInfo = semanticModel.GetSymbolInfo(invocation, ct);
        var candidates = symbolInfo.Symbol is IMethodSymbol s
            ? [s]
            : symbolInfo.CandidateSymbols.OfType<IMethodSymbol>().ToImmutableArray();

        var duckAsCall = candidates.FirstOrDefault(c => IsDuckAs(c, compilation));
        if (duckAsCall is not null)
            return AnalyzeDuckAsCall(semanticModel, invocation, duckAsCall, ct);

        var duckMethod = candidates
            .Select(c => c.OriginalDefinition)
            .FirstOrDefault(c => c.DeclaringSyntaxReferences.Length > 0 && IsDuckTyped(c));
        if (duckMethod is null || !ValidateDuckTypedMethod(duckMethod, Location.None, diagnostics: null))
            return null;

        var arguments = MapArguments(invocation.ArgumentList, duckMethod);
        if (arguments is null)
            return null;

        if (GetConstraintTypeParameters(duckMethod) is { IsEmpty: false } constraintTypeParameters)
            return AnalyzeConstraintCall(semanticModel, duckMethod, constraintTypeParameters, arguments, compilation, ct);

        var duckArguments = new List<(IParameterSymbol Parameter, ExpressionSyntax Expression, INamedTypeSymbol ConcreteType)>();
        var passedThrough = new Dictionary<int, (ITypeSymbol ConcreteType, string? AdapterName)>();
        foreach (var parameter in GetDuckParameters(duckMethod))
        {
            if (!arguments.TryGetValue(parameter.Ordinal, out var expression))
            {
                if (duckMethod.IsGenericMethod)
                    return null;
                continue;
            }

            // Omitted arguments, null/default literals and values already typed as the interface bind to a fallback variant keeping that parameter as is.
            var argumentType = GetArgumentType(semanticModel, expression, compilation, ct);
            if (!duckMethod.IsGenericMethod && GetDuckParameters(duckMethod).Length <= MaxFallbackVariantParameters &&
                (argumentType is null || SymbolEqualityComparer.Default.Equals(argumentType, parameter.Type)))
                continue;

            if (argumentType is IArrayTypeSymbol array && !duckMethod.IsGenericMethod &&
                compilation.ClassifyCommonConversion(array, parameter.Type) is { IsImplicit: true, IsUserDefined: false })
            {
                passedThrough[parameter.Ordinal] = (array, null);
                continue;
            }

            if (argumentType is not INamedTypeSymbol concreteType ||
                concreteType.TypeKind == TypeKind.Error ||
                (duckMethod.IsGenericMethod && ContainsAnyTypeParameter(concreteType)))
                return null;

            duckArguments.Add((parameter, expression, concreteType));
        }

        if (duckArguments.Count == 0 && passedThrough.Count == 0)
            return null;

        var diagnostics = ImmutableArray.CreateBuilder<Diagnostic>();
        var targetMethod = duckMethod;
        if (duckMethod.IsGenericMethod)
        {
            foreach (var (parameter, expression, concreteType) in duckArguments)
            {
                var shape = (INamedTypeSymbol)parameter.Type;
                if (!concreteType.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i.OriginalDefinition, shape.OriginalDefinition)) &&
                    FindUnsupportedMemberDiagnostic(expression, shape) is { } unsupported)
                    diagnostics.Add(unsupported);
                else if (concreteType.IsAnonymousType)
                    diagnostics.Add(Diagnostic.Create(Diagnostics.ShapeMismatch, expression.GetLocation(), concreteType.ToDisplayString(),
                        parameter.Type.ToDisplayString(), "anonymous types are not supported by generic [DuckTyped] methods"));
            }
            if (diagnostics.Count > 0)
                return DiagnosticsOnly(diagnostics);

            var constructed = TypeArgumentInference.TryConstruct(duckMethod, duckArguments.Select(a => (a.Parameter, a.ConcreteType)));
            if (constructed is null)
            {
                var failing = duckArguments.FirstOrDefault(a => ShapeMatcher.FindMismatch((INamedTypeSymbol)a.Parameter.Type, a.ConcreteType, compilation) is not null);
                if (failing.Parameter is null)
                    failing = duckArguments[0];
                diagnostics.Add(Diagnostic.Create(Diagnostics.ShapeMismatch, failing.Expression.GetLocation(),
                    failing.ConcreteType.ToDisplayString(), failing.Parameter.Type.ToDisplayString(),
                    ShapeMatcher.FindMismatch((INamedTypeSymbol)failing.Parameter.Type, failing.ConcreteType, compilation)
                    ?? $"type arguments for '{duckMethod.Name}' could not be inferred"));
                return DiagnosticsOnly(diagnostics);
            }
            targetMethod = constructed;
        }

        var adapters = ImmutableArray.CreateBuilder<GeneratedFile>();
        var resolved = new Dictionary<int, (ITypeSymbol ConcreteType, string? AdapterName)>(passedThrough);
        foreach (var (parameter, expression, concreteType) in duckArguments)
        {
            var shape = (INamedTypeSymbol)WithoutNullability(targetMethod.Parameters[parameter.Ordinal].Type);
            if (VerifyArgument(expression, shape, concreteType, compilation, out var implementsDirectly) is { } diagnostic)
            {
                diagnostics.Add(diagnostic);
                continue;
            }

            var adapter = implementsDirectly ? null : CreateAdapter(shape, concreteType, compilation);
            if (adapter is not null)
                adapters.Add(adapter);
            resolved[parameter.Ordinal] = (concreteType, adapter?.Name);
        }

        if (diagnostics.Count > 0)
            return DiagnosticsOnly(diagnostics);

        if (duckMethod.IsGenericMethod)
        {
            return adapters.Count == 0
                ? null
                : new CallSiteOutput(null, new EquatableArray<GeneratedFile>(adapters.ToImmutable()),
                    CreateDuckOverload(duckMethod, targetMethod, resolved), default);
        }

        var location = semanticModel.GetInterceptableLocation(invocation, ct);
        if (location is null)
            return null;

        return new CallSiteOutput(CreateInterceptor(location, duckMethod, resolved),
            new EquatableArray<GeneratedFile>(adapters.ToImmutable()), null, default);
    }

    // A name used as a value, e.g. 'Ops.Describe' in 'Func<Person, string> f = Ops.Describe;' or 'items.Select(Ops.Describe)'.
    private static ExpressionSyntax? AsMethodGroup(SyntaxNode node)
    {
        if (node is not SimpleNameSyntax name || name.Parent is null)
            return null;

        var expression = name.Parent is MemberAccessExpressionSyntax member && member.Name == name ? (ExpressionSyntax)member : name;
        if (expression.Parent is null)
            return null;

        return expression.Parent switch
        {
            InvocationExpressionSyntax invocation when invocation.Expression == expression => null,
            MemberAccessExpressionSyntax or MemberBindingExpressionSyntax or NameSyntax or TypeSyntax => null,
            _ => expression,
        };
    }

    private static string GetMethodGroupName(ExpressionSyntax expression) => expression switch
    {
        MemberAccessExpressionSyntax member => member.Name.Identifier.Text,
        SimpleNameSyntax name => name.Identifier.Text,
        _ => string.Empty,
    };

    private static CallSiteOutput? AnalyzeMethodGroup(ExpressionSyntax expression, Compilation compilation, CancellationToken ct)
    {
        if (!compilation.ContainsSyntaxTree(expression.SyntaxTree))
            return null;

        var semanticModel = compilation.GetSemanticModel(expression.SyntaxTree);
        var symbolInfo = semanticModel.GetSymbolInfo(expression, ct);
        var duckMethod = (symbolInfo.Symbol as IMethodSymbol ?? symbolInfo.CandidateSymbols.OfType<IMethodSymbol>().FirstOrDefault())?.OriginalDefinition;
        if (duckMethod is null || duckMethod.IsGenericMethod || duckMethod.DeclaringSyntaxReferences.Length == 0 ||
            !IsDuckTyped(duckMethod) || !ValidateDuckTypedMethod(duckMethod, Location.None, diagnostics: null))
            return null;

        if (semanticModel.GetTypeInfo(expression, ct).ConvertedType is not INamedTypeSymbol { DelegateInvokeMethod: { } invoke } ||
            invoke.Parameters.Length != duckMethod.Parameters.Length)
            return null;

        var adapters = ImmutableArray.CreateBuilder<GeneratedFile>();
        var resolved = new Dictionary<int, (ITypeSymbol ConcreteType, string? AdapterName)>();
        foreach (var parameter in GetDuckParameters(duckMethod))
        {
            if (invoke.Parameters[parameter.Ordinal].Type is not INamedTypeSymbol concreteType ||
                concreteType.TypeKind == TypeKind.Error || ContainsAnyTypeParameter(concreteType) ||
                SymbolEqualityComparer.Default.Equals(concreteType, parameter.Type))
                continue;

            var shape = (INamedTypeSymbol)WithoutNullability(parameter.Type);
            if (VerifyArgument(expression, shape, concreteType, compilation, out var implementsDirectly) is not null || implementsDirectly)
                continue;

            var adapter = CreateAdapter(shape, concreteType, compilation);
            adapters.Add(adapter);
            resolved[parameter.Ordinal] = (concreteType, adapter.Name);
        }

        return resolved.Count == 0
            ? null
            : new CallSiteOutput(null, new EquatableArray<GeneratedFile>(adapters.ToImmutable()),
                CreateDuckOverload(duckMethod, duckMethod, resolved), default);
    }

    private static CallSiteOutput? AnalyzeConstraintCall(SemanticModel semanticModel, IMethodSymbol duckMethod,
        ImmutableArray<ITypeParameterSymbol> constraintTypeParameters, Dictionary<int, ExpressionSyntax> arguments,
        Compilation compilation, CancellationToken ct)
    {
        var diagnostics = ImmutableArray.CreateBuilder<Diagnostic>();
        var adapters = ImmutableArray.CreateBuilder<GeneratedFile>();
        var bindings = new Dictionary<ITypeParameterSymbol, (INamedTypeSymbol ConcreteType, string? AdapterName)>(SymbolEqualityComparer.Default);

        foreach (var typeParameter in constraintTypeParameters)
        {
            var boundParameters = duckMethod.Parameters
                .Where(p => SymbolEqualityComparer.Default.Equals(p.Type, typeParameter))
                .ToImmutableArray();

            var argumentTypes = boundParameters
                .Select(p => arguments.TryGetValue(p.Ordinal, out var expression)
                    ? (Expression: expression, Type: GetArgumentType(semanticModel, expression, compilation, ct))
                    : default)
                .ToImmutableArray();

            if (argumentTypes.Any(a => a.Type is not INamedTypeSymbol { TypeKind: not TypeKind.Error } type || ContainsAnyTypeParameter(type)) ||
                argumentTypes.Select(a => a.Type).Distinct(SymbolEqualityComparer.Default).Count() != 1)
                return null;

            var concreteType = (INamedTypeSymbol)argumentTypes[0].Type!;
            var shape = (INamedTypeSymbol)SubstituteTypeParameter(typeParameter.ConstraintTypes[0], typeParameter, concreteType);

            // A type satisfying the constraint itself needs no adapter; the call compiles as it is.
            if (concreteType.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i, shape)))
            {
                bindings[typeParameter] = (concreteType, null);
                continue;
            }

            var location = argumentTypes[0].Expression.GetLocation();
            if (StaticShapeMatcher.FindUnsupportedMember(shape) is { } unsupportedStatic)
            {
                diagnostics.Add(Diagnostic.Create(Diagnostics.UnsupportedShapeMember, location, shape.ToDisplayString(),
                    unsupportedStatic.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat)));
                continue;
            }

            // Static abstract members are the point here, but an instance member using the self type can't be forwarded.
            if (ShapeMatcher.GetShapeMembers(shape)
                    .FirstOrDefault(m => m is IMethodSymbol { IsGenericMethod: true } || UsesSelfType(m, concreteType)) is { } unsupportedInstance)
            {
                diagnostics.Add(Diagnostic.Create(Diagnostics.UnsupportedShapeMember, location, shape.ToDisplayString(),
                    unsupportedInstance.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat)));
                continue;
            }

            var mismatch = StaticShapeMatcher.FindMismatch(shape, concreteType, compilation) ??
                           ShapeMatcher.FindMismatch(shape, concreteType, compilation);
            if (mismatch is not null)
            {
                diagnostics.Add(Diagnostic.Create(Diagnostics.ShapeMismatch, location, concreteType.ToDisplayString(),
                    shape.ToDisplayString(), mismatch));
                continue;
            }

            if (GetUnsupportedStructKind(concreteType, implementsDirectly: false) is { } unsupportedStruct)
            {
                diagnostics.Add(Diagnostic.Create(Diagnostics.UnsupportedStructArgument, location, concreteType.ToDisplayString(),
                    shape.ToDisplayString(), unsupportedStruct));
                continue;
            }

            var adapterName = AdapterEmitter.GetAdapterName(shape, concreteType);
            adapters.Add(new GeneratedFile(adapterName, SelfShapeAdapterEmitter.Emit(shape, concreteType, adapterName, compilation)));
            bindings[typeParameter] = (concreteType, adapterName);
        }

        if (diagnostics.Count > 0)
            return DiagnosticsOnly(diagnostics);

        if (bindings.Count != constraintTypeParameters.Length || bindings.Values.All(b => b.AdapterName is null))
            return null;

        var overload = CreateConstraintOverload(duckMethod, bindings);
        return overload is null
            ? null
            : new CallSiteOutput(null, new EquatableArray<GeneratedFile>(adapters.ToImmutable()), overload, default);
    }

    // Only members whose signature is free of the self type can be forwarded by the generated adapter.
    private static bool UsesSelfType(ISymbol member, INamedTypeSymbol self) => member switch
    {
        IMethodSymbol method => Mentions(method.ReturnType, self) || method.Parameters.Any(p => Mentions(p.Type, self)),
        IPropertySymbol property => Mentions(property.Type, self) || property.Parameters.Any(p => Mentions(p.Type, self)),
        IEventSymbol @event => Mentions(@event.Type, self),
        _ => false,
    };

    private static bool Mentions(ITypeSymbol type, INamedTypeSymbol self) =>
        SymbolEqualityComparer.Default.Equals(type, self) ||
        (type is INamedTypeSymbol named && named.TypeArguments.Any(t => Mentions(t, self))) ||
        (type is IArrayTypeSymbol array && Mentions(array.ElementType, self));

    private static ITypeSymbol SubstituteTypeParameter(ITypeSymbol type, ITypeParameterSymbol typeParameter, ITypeSymbol replacement) => type switch
    {
        ITypeParameterSymbol tp when SymbolEqualityComparer.Default.Equals(tp, typeParameter) => replacement,
        INamedTypeSymbol { IsGenericType: true } named =>
            named.OriginalDefinition.Construct([.. named.TypeArguments.Select(t => SubstituteTypeParameter(t, typeParameter, replacement))]),
        _ => type,
    };

    private static OverloadMember? CreateConstraintOverload(IMethodSymbol method,
        Dictionary<ITypeParameterSymbol, (INamedTypeSymbol ConcreteType, string? AdapterName)> bindings)
    {
        string? Bound(ITypeSymbol type) =>
            type is ITypeParameterSymbol tp && bindings.TryGetValue(tp, out var binding) ? binding.ConcreteType.ToDisplayString() : null;

        if (method.Parameters.Any(p => Bound(p.Type) is null && ContainsAnyTypeParameter(p.Type)) ||
            (Bound(method.ReturnType) is null && ContainsAnyTypeParameter(method.ReturnType)))
            return null;

        var parameters = string.Join(", ", method.Parameters.Select(p =>
            Utilities.Parameter(p, Bound(p.Type) ?? p.Type.ToDisplayString()) + Utilities.DefaultValue(p)));

        var arguments = string.Join(", ", method.Parameters.Select(p =>
            p.Type is ITypeParameterSymbol tp && bindings.TryGetValue(tp, out var binding) && binding.AdapterName is not null
                ? $"new global::{GeneratedNamespace}.{binding.AdapterName}({Utilities.Identifier(p.Name)})"
                : Utilities.Argument(p)));

        var typeArguments = string.Join(", ", method.TypeParameters.Select(tp =>
            bindings[tp].AdapterName is { } adapter ? $"global::{GeneratedNamespace}.{adapter}" : bindings[tp].ConcreteType.ToDisplayString()));

        var returnType = Bound(method.ReturnType) ?? method.ReturnType.ToDisplayString();
        var call = $"{method.Name}<{typeArguments}>({arguments})";

        // A method returning the constrained type parameter returns an adapter, which converts back to the argument's type.
        var body = call;
        if (!method.ReturnsVoid && method.ReturnType is ITypeParameterSymbol returnedParameter &&
            bindings.TryGetValue(returnedParameter, out var returnBinding) && returnBinding.AdapterName is not null)
            body = $"({returnBinding.ConcreteType.ToDisplayString()})({call})";

        var accessibility = method.DeclaredAccessibility is Accessibility.Public or Accessibility.Protected or Accessibility.ProtectedOrInternal &&
                            !bindings.Values.All(b => IsPubliclyVisible(b.ConcreteType))
            ? "internal"
            : Utilities.AccessibilityKeyword(method.DeclaredAccessibility);

        var member =
            $"{EditorBrowsableNever} {accessibility} {(method.IsStatic ? "static " : "")}{returnType} {method.Name}({parameters}) => {body};";

        var (prefix, suffix) = TypeWrapper.WrapTemplate(method.ContainingType);
        return new OverloadMember(
            $"IfItQuacks.Overloads.{SanitizeHintName(method.ContainingType.ToDisplayString())}.{method.Name}.g.cs",
            Header + prefix, suffix, member);
    }

    private static CallSiteOutput? AnalyzeDuckAsCall(SemanticModel semanticModel, InvocationExpressionSyntax invocation,
        IMethodSymbol duckAsCall, CancellationToken ct)
    {
        var typeArgument = duckAsCall.TypeArguments[0];
        if (WithoutNullability(typeArgument) is not INamedTypeSymbol { TypeKind: TypeKind.Interface } shape)
        {
            return DiagnosticsOnly([Diagnostic.Create(Diagnostics.ConversionTargetNotShape, invocation.GetLocation(),
                typeArgument.ToDisplayString())]);
        }

        if (invocation.ArgumentList.Arguments.Count != 1 || ContainsAnyTypeParameter(shape))
            return null;

        var argExpr = invocation.ArgumentList.Arguments[0].Expression;
        if (GetArgumentType(semanticModel, argExpr, semanticModel.Compilation, ct) is not INamedTypeSymbol concreteType ||
            concreteType.TypeKind == TypeKind.Error || ContainsAnyTypeParameter(concreteType))
            return null;

        if (VerifyArgument(argExpr, shape, concreteType, semanticModel.Compilation, out var implementsDirectly) is { } diagnostic)
            return DiagnosticsOnly([diagnostic]);

        var location = semanticModel.GetInterceptableLocation(invocation, ct);
        if (location is null)
            return null;

        var shapeTypeName = shape.ToDisplayString();
        var adapter = implementsDirectly ? null : CreateAdapter(shape, concreteType, semanticModel.Compilation);
        var argument = concreteType.IsAnonymousType ? "value" : $"({concreteType.ToDisplayString()})value";
        var result = adapter is null ? "value" : $"new global::{GeneratedNamespace}.{adapter.Name}({argument})";

        var interceptor =
            $"        {location.GetInterceptsLocationAttributeSyntax()}\n" +
            $"        public static global::{shapeTypeName} Interceptor_{InterceptorIndexPlaceholder}(object value) => (global::{shapeTypeName})({result});\n";

        return new CallSiteOutput(interceptor,
            adapter is null ? default : new EquatableArray<GeneratedFile>([adapter]), null, default);
    }

    private static Dictionary<int, ExpressionSyntax>? MapArguments(ArgumentListSyntax argumentList, IMethodSymbol method)
    {
        var arguments = new Dictionary<int, ExpressionSyntax>();
        for (var i = 0; i < argumentList.Arguments.Count; i++)
        {
            var argument = argumentList.Arguments[i];
            IParameterSymbol? parameter;
            if (argument.NameColon is { } nameColon)
                parameter = method.Parameters.FirstOrDefault(p => p.Name == nameColon.Name.Identifier.ValueText);
            else if (i < method.Parameters.Length)
                parameter = method.Parameters[i];
            else
                parameter = method.Parameters.LastOrDefault(p => p.IsParams);

            if (parameter is null)
                return null;

            arguments[parameter.Ordinal] = argument.Expression;
        }
        return arguments;
    }

    // A lambda or method group has no type of its own, so its natural delegate type stands in for it.
    private static ITypeSymbol? GetArgumentType(SemanticModel semanticModel, ExpressionSyntax expression, Compilation compilation, CancellationToken ct)
    {
        var typeInfo = semanticModel.GetTypeInfo(expression, ct);
        if (typeInfo.Type is { } type)
            return type;

        if (typeInfo.ConvertedType is { TypeKind: TypeKind.Delegate } converted)
            return converted;

        return expression is AnonymousFunctionExpressionSyntax or SimpleNameSyntax or MemberAccessExpressionSyntax &&
               GetMethodSymbol(semanticModel.GetSymbolInfo(expression, ct)) is { } method
            ? NaturalDelegateType(method, compilation)
            : null;
    }

    private static IMethodSymbol? GetMethodSymbol(SymbolInfo symbolInfo) =>
        (symbolInfo.Symbol ?? symbolInfo.CandidateSymbols.SingleOrDefault()) as IMethodSymbol;

    // Mirrors the compiler's natural type for lambdas and method groups: Action for void, Func otherwise.
    private static INamedTypeSymbol? NaturalDelegateType(IMethodSymbol method, Compilation compilation)
    {
        if (method.IsGenericMethod || method.RefKind != RefKind.None || method.Parameters.Length > 15 ||
            method.Parameters.Any(p => p.RefKind != RefKind.None) ||
            ContainsErrorType(method.ReturnType) || method.Parameters.Any(p => ContainsErrorType(p.Type)))
            return null;

        var typeArguments = method.Parameters.Select(p => p.Type).ToList();
        if (method.ReturnsVoid)
        {
            var action = compilation.GetTypeByMetadataName(typeArguments.Count == 0 ? "System.Action" : $"System.Action`{typeArguments.Count}");
            return typeArguments.Count == 0 ? action : action?.Construct([.. typeArguments]);
        }

        typeArguments.Add(method.ReturnType);
        return compilation.GetTypeByMetadataName($"System.Func`{typeArguments.Count}")?.Construct([.. typeArguments]);
    }

    private static bool ContainsErrorType(ITypeSymbol type) => type switch
    {
        { TypeKind: TypeKind.Error } => true,
        INamedTypeSymbol named => named.TypeArguments.Any(ContainsErrorType),
        IArrayTypeSymbol array => ContainsErrorType(array.ElementType),
        _ => false,
    };

    private static Diagnostic? VerifyArgument(ExpressionSyntax argExpr, INamedTypeSymbol shape, INamedTypeSymbol concreteType,
        Compilation compilation, out bool implementsDirectly)
    {
        // Covers explicit implementations and variance (e.g. List<string> as IEnumerable<object>), which structural matching can't see.
        var conversion = compilation.ClassifyCommonConversion(concreteType, shape);
        implementsDirectly = conversion.IsImplicit && !conversion.IsUserDefined;
        if (implementsDirectly)
            return null;

        if (FindUnsupportedMemberDiagnostic(argExpr, shape) is { } unsupported)
            return unsupported;

        var mismatch = ShapeMatcher.FindMismatch(shape, concreteType, compilation) ??
                       (concreteType.IsAnonymousType && AdapterEmitter.FindUnnameableProperty(concreteType) is { } property
                           ? $"property '{property}' has a type that contains an anonymous type"
                           : null);
        if (mismatch is not null)
        {
            return Diagnostic.Create(Diagnostics.ShapeMismatch, argExpr.GetLocation(),
                concreteType.ToDisplayString(), shape.ToDisplayString(), mismatch);
        }

        var unsupportedStructKind = GetUnsupportedStructKind(concreteType, implementsDirectly);
        return unsupportedStructKind is null
            ? null
            : Diagnostic.Create(Diagnostics.UnsupportedStructArgument, argExpr.GetLocation(),
                concreteType.ToDisplayString(), shape.ToDisplayString(), unsupportedStructKind);
    }

    private static Diagnostic? FindUnsupportedMemberDiagnostic(ExpressionSyntax argExpr, INamedTypeSymbol shape) =>
        ShapeMatcher.FindUnsupportedMember(shape) is { } member
            ? Diagnostic.Create(Diagnostics.UnsupportedShapeMember, argExpr.GetLocation(), shape.ToDisplayString(),
                member.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat))
            : null;

    private static CallSiteOutput DiagnosticsOnly(IEnumerable<Diagnostic> diagnostics) =>
        new(null, default, null, new EquatableArray<Diagnostic>(diagnostics.ToImmutableArray()));

    private static GeneratedFile CreateAdapter(INamedTypeSymbol shape, INamedTypeSymbol concreteType, Compilation compilation)
    {
        var name = AdapterEmitter.GetAdapterName(shape, concreteType);
        return new GeneratedFile(name, AdapterEmitter.Emit(shape, concreteType, name, compilation));
    }

    private static ImmutableArray<IParameterSymbol> GetDuckParameters(IMethodSymbol method) =>
        method.Parameters
            .Where(p => p is { RefKind: RefKind.None, Type.TypeKind: TypeKind.Interface })
            .ToImmutableArray();

    private static bool IsDuckTyped(IMethodSymbol method) =>
        method.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == DuckTypedAttributeName);

    private static bool IsDuckAs(IMethodSymbol method, Compilation compilation) =>
        method.Name == DuckAsMethodName &&
        method.ContainingType.ToDisplayString() == DuckTypeName &&
        SymbolEqualityComparer.Default.Equals(method.ContainingAssembly, compilation.Assembly);

    private static bool IsInGenericType(INamedTypeSymbol type) => EnclosingTypes(type).Any(t => t.IsGenericType);

    private static bool IsInFileLocalType(INamedTypeSymbol type) => EnclosingTypes(type).Any(t => t.IsFileLocal);

    private static IEnumerable<INamedTypeSymbol> EnclosingTypes(INamedTypeSymbol type)
    {
        for (var t = type; t is not null; t = t.ContainingType)
            yield return t;
    }

    // A struct implementing the shape is boxed by the compiler itself, so only adapter-wrapped mutable structs would silently lose mutations.
    private static string? GetUnsupportedStructKind(INamedTypeSymbol type, bool implementsDirectly)
    {
        if (type.IsRefLikeType)
            return "ref structs cannot be converted to an interface";

        if (type.IsValueType && !type.IsReadOnly && !implementsDirectly)
            return "mutable structs are copied into an adapter, so mutations made through the shape would be lost";

        return null;
    }

    private static string? GetInvokedName(InvocationExpressionSyntax invocation) => invocation.Expression switch
    {
        SimpleNameSyntax name => name.Identifier.Text,
        MemberAccessExpressionSyntax member => member.Name.Identifier.Text,
        _ => null,
    };

    private static void EmitDuckTypedMethod(SourceProductionContext spc, DuckTypedMethodOutput method)
    {
        foreach (var diagnostic in method.Diagnostics)
            spc.ReportDiagnostic(diagnostic);

        if (method.Fallback is not null)
            spc.AddSource(method.Fallback.Name, SourceText.From(method.Fallback.Source, Encoding.UTF8));
    }

    private static void EmitCallSites(SourceProductionContext spc, ImmutableArray<CallSiteOutput?> sites)
    {
        var adapters = new SortedDictionary<string, string>(StringComparer.Ordinal);
        var overloadFiles = new SortedDictionary<string, (OverloadMember Template, SortedSet<string> Members)>(StringComparer.Ordinal);
        var interceptors = new StringBuilder();
        var interceptorCount = 0;

        foreach (var site in sites.OfType<CallSiteOutput>())
        {
            foreach (var diagnostic in site.Diagnostics)
                spc.ReportDiagnostic(diagnostic);

            foreach (var adapter in site.Adapters)
                adapters[adapter.Name] = adapter.Source;

            if (site.Overload is { } overload)
            {
                if (!overloadFiles.TryGetValue(overload.FileName, out var file))
                    overloadFiles[overload.FileName] = file = (overload, new SortedSet<string>(StringComparer.Ordinal));
                file.Members.Add(overload.Member);
            }

            if (site.Interceptor is not null)
            {
                interceptorCount++;
                interceptors.AppendLine();
                interceptors.Append(site.Interceptor.Replace(InterceptorIndexPlaceholder, interceptorCount.ToString(CultureInfo.InvariantCulture)));
            }
        }

        foreach (var (template, members) in overloadFiles.Values)
        {
            var indent = template.Prefix.Substring(template.Prefix.LastIndexOf('\n') + 1);
            var source = template.Prefix + string.Join("\n" + indent, members) + template.Suffix;
            spc.AddSource(template.FileName, SourceText.From(source, Encoding.UTF8));
        }

        if (interceptorCount > 0)
        {
            var sb = new StringBuilder(Header);
            sb.AppendLine(EmbeddedSources.InterceptsLocationAttributePolyfill);
            sb.AppendLine("namespace " + GeneratedNamespace);
            sb.AppendLine("{");
            sb.AppendLine("    file static class IfItQuacksInterceptors");
            sb.AppendLine("    {");
            sb.Append(interceptors);
            sb.AppendLine("    }");
            sb.AppendLine("}");
            spc.AddSource("IfItQuacks.Interceptors.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        if (adapters.Count > 0)
        {
            var sb = new StringBuilder(Header);
            sb.AppendLine("namespace " + GeneratedNamespace);
            sb.AppendLine("{");
            foreach (var adapter in adapters.Values)
                sb.Append(adapter);
            sb.AppendLine("}");
            spc.AddSource("IfItQuacks.Adapters.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }
    }

    private const int MaxFallbackVariantParameters = 4;

    private static GeneratedFile CreateFallbackOverload(IMethodSymbol method)
    {
        var duckParameters = GetDuckParameters(method);
        // One variant per subset of generic parameters, so null, default and omitted arguments can keep the interface type.
        var subsets = duckParameters.Length > MaxFallbackVariantParameters
            ? [duckParameters]
            : Enumerable.Range(1, (1 << duckParameters.Length) - 1)
                .Select(mask => duckParameters.Where((_, i) => (mask & (1 << i)) != 0).ToImmutableArray());

        var methodSource = string.Join("\n\n", subsets.Select(subset => CreateFallbackVariant(method, subset)));
        if (NeedsForwarder(method))
            methodSource += "\n\n" + CreateForwarder(method);

        return new GeneratedFile(
            $"IfItQuacks.Fallback.{SanitizeHintName(method.ContainingType.ToDisplayString())}.{method.Name}.g.cs",
            Header + TypeWrapper.WrapInContainingScope(method.ContainingType, methodSource));
    }

    private static string CreateFallbackVariant(IMethodSymbol method, ImmutableArray<IParameterSymbol> genericParameters)
    {
        var typeParameterNames = genericParameters.ToDictionary(p => p.Ordinal, FallbackTypeParameterName);

        var parameters = string.Join(", ", method.Parameters.Select(p => typeParameterNames.TryGetValue(p.Ordinal, out var name)
            ? Utilities.Parameter(p, name) + GenericDefaultValue(p)
            : Utilities.Parameter(p, p.Type.ToDisplayString()) + Utilities.DefaultValue(p)));
        // Calls that couldn't be verified at compile time (e.g. from generic code) still work if the value implements the interface at runtime.
        var arguments = string.Join(", ", method.Parameters.Select(p => typeParameterNames.TryGetValue(p.Ordinal, out var name)
            ? RuntimeCast(p, name)
            : Utilities.Argument(p)));

        return $$"""
            {{EditorBrowsableNever}}
            {{Utilities.AccessibilityKeyword(method.DeclaredAccessibility)}} {{(method.IsStatic ? "static " : "")}}{{method.ReturnType.ToDisplayString()}} {{method.Name}}<{{string.Join(", ", typeParameterNames.Values)}}>({{parameters}})
            {
                {{(method.ReturnsVoid ? "" : "return ")}}{{method.Name}}({{arguments}});
            }
            """;
    }

    // Interceptors live in their own namespace, so methods they can't access are called through an internal forwarder on the containing type.
    private static bool NeedsForwarder(IMethodSymbol method) =>
        method.DeclaredAccessibility is Accessibility.Private or Accessibility.Protected or Accessibility.ProtectedAndInternal;

    private static string ForwarderName(IMethodSymbol method) => $"__IfItQuacks_{method.Name}";

    private static string CreateForwarder(IMethodSymbol method)
    {
        var parameters = string.Join(", ", method.Parameters.Select(p => Utilities.Parameter(p, p.Type.ToDisplayString())));
        var arguments = string.Join(", ", method.Parameters.Select(Utilities.Argument));
        var modifiers = (method.IsStatic ? "static " : "") + (method.IsReadOnly ? "readonly " : "");
        return $"{EditorBrowsableNever}\n" +
               $"internal {modifiers}{method.ReturnType.ToDisplayString()} {ForwarderName(method)}({parameters}) => {method.Name}({arguments});";
    }

    // Interceptors must keep the intercepted signature, so a generic fallback can't return the per-call inferred type; concrete overloads can.
    private static OverloadMember CreateDuckOverload(IMethodSymbol method, IMethodSymbol constructed,
        Dictionary<int, (ITypeSymbol ConcreteType, string? AdapterName)> duckArguments)
    {
        var accessibility = method.DeclaredAccessibility is Accessibility.Public or Accessibility.Protected or Accessibility.ProtectedOrInternal &&
                            !duckArguments.Values.All(a => IsPubliclyVisible(a.ConcreteType))
            ? "internal"
            : Utilities.AccessibilityKeyword(method.DeclaredAccessibility);

        var parameters = string.Join(", ", constructed.Parameters.Select(p =>
            Utilities.Parameter(p, duckArguments.TryGetValue(p.Ordinal, out var duck) ? duck.ConcreteType.ToDisplayString() : p.Type.ToDisplayString()) +
            Utilities.DefaultValue(p)));

        var arguments = string.Join(", ", constructed.Parameters.Select(p =>
            duckArguments.TryGetValue(p.Ordinal, out var duck) && duck.AdapterName is not null
                ? $"new global::{GeneratedNamespace}.{duck.AdapterName}({Utilities.Identifier(p.Name)})"
                : Utilities.Argument(p)));

        var typeArguments = constructed.TypeArguments.IsEmpty
            ? ""
            : $"<{string.Join(", ", constructed.TypeArguments.Select(t => t.ToDisplayString()))}>";
        var member =
            $"{EditorBrowsableNever} {accessibility} {(method.IsStatic ? "static " : "")}{constructed.ReturnType.ToDisplayString()} {method.Name}({parameters}) => " +
            $"{method.Name}{typeArguments}({arguments});";

        var (prefix, suffix) = TypeWrapper.WrapTemplate(method.ContainingType);
        return new OverloadMember(
            $"IfItQuacks.Overloads.{SanitizeHintName(method.ContainingType.ToDisplayString())}.{method.Name}.g.cs",
            Header + prefix, suffix, member);
    }

    private static string CreateInterceptor(InterceptableLocation location, IMethodSymbol method,
        Dictionary<int, (ITypeSymbol ConcreteType, string? AdapterName)> duckArguments)
    {
        // Anonymous types can't be named in the signature, so the interceptor stays generic like the fallback it replaces.
        var isGeneric = duckArguments.Values.Any(d => d.ConcreteType.IsAnonymousType);
        var parameters = method.Parameters.Select(p =>
        {
            if (!duckArguments.TryGetValue(p.Ordinal, out var duck))
                return Utilities.Parameter(p, p.Type.ToDisplayString());
            return Utilities.Parameter(p, isGeneric ? FallbackTypeParameterName(p) : duck.ConcreteType.ToDisplayString());
        });
        if (!method.IsStatic)
        {
            // Struct receivers are passed by reference, so mutations made by the method reach the caller's value.
            var receiverRefKind = method.IsReadOnly ? "in " : "ref ";
            parameters = parameters.Prepend($"this {(method.ContainingType.IsValueType ? receiverRefKind : "")}global::{method.ContainingType.ToDisplayString()} @this");
        }

        // Casting to the shape interface makes overload resolution pick the real method instead of the generated generic fallback.
        var arguments = method.Parameters.Select(p =>
        {
            if (!duckArguments.TryGetValue(p.Ordinal, out var duck))
                return Utilities.Argument(p);

            var name = Utilities.Identifier(p.Name);
            if (isGeneric)
                name = duck.ConcreteType.IsAnonymousType ? $"(object){name}!" : $"({duck.ConcreteType.ToDisplayString()})(object){name}!";
            var value = duck.AdapterName is null ? name : $"new global::{GeneratedNamespace}.{duck.AdapterName}({name})";
            return $"(global::{WithoutNullability(p.Type).ToDisplayString()})({value})";
        });
        var typeParameters = isGeneric ? $"<{string.Join(", ", duckArguments.Keys.OrderBy(o => o).Select(o => FallbackTypeParameterName(method.Parameters[o])))}>" : "";

        var receiver = method.IsStatic ? $"global::{method.ContainingType.ToDisplayString()}" : "@this";
        var call = $"{receiver}.{(NeedsForwarder(method) ? ForwarderName(method) : method.Name)}({string.Join(", ", arguments)});";

        var sb = new StringBuilder();
        sb.AppendLine("        " + location.GetInterceptsLocationAttributeSyntax());
        sb.AppendLine($"        public static {method.ReturnType.ToDisplayString()} Interceptor_{InterceptorIndexPlaceholder}{typeParameters}({string.Join(", ", parameters)})");
        sb.AppendLine("        {");
        sb.AppendLine(method.ReturnsVoid ? $"            {call}" : $"            return {call}");
        sb.AppendLine("        }");
        return sb.ToString();
    }

    private static string GenericDefaultValue(IParameterSymbol parameter) => parameter.HasExplicitDefaultValue ? " = default!" : "";

    private static string RuntimeCast(IParameterSymbol parameter, string typeParameterName)
    {
        var identifier = Utilities.Identifier(parameter.Name);
        var interfaceName = $"global::{WithoutNullability(parameter.Type).ToDisplayString()}";
        var allowNull = parameter.Type.NullableAnnotation == NullableAnnotation.Annotated ? $"{identifier} is null ? null : " : "";
        return $"{identifier} is {interfaceName} __duck{parameter.Ordinal} ? __duck{parameter.Ordinal} : {allowNull}" +
               $"throw new global::IfItQuacks.DuckTypeMismatchException(typeof({typeParameterName}), typeof({interfaceName}))";
    }

    private static ITypeSymbol WithoutNullability(ITypeSymbol type) => type.WithNullableAnnotation(NullableAnnotation.NotAnnotated);

    private static string FallbackTypeParameterName(IParameterSymbol parameter) => $"TDuck{parameter.Ordinal}";

    private static string SanitizeHintName(string name) => name.Replace('.', '_').Replace('<', '_').Replace('>', '_').Replace(',', '_').Replace(' ', '_');

    private static bool IsPubliclyVisible(ITypeSymbol type) => type switch
    {
        INamedTypeSymbol named => IsDeclaredPublic(named) && named.TypeArguments.All(IsPubliclyVisible),
        IArrayTypeSymbol array => IsPubliclyVisible(array.ElementType),
        _ => true,
    };

    private static bool IsDeclaredPublic(INamedTypeSymbol type)
    {
        for (var t = type; t is not null; t = t.ContainingType)
            if (t.DeclaredAccessibility != Accessibility.Public)
                return false;
        return true;
    }

    private static bool ContainsTypeParameter(ITypeSymbol type, ITypeParameterSymbol typeParameter) => type switch
    {
        ITypeParameterSymbol tp => SymbolEqualityComparer.Default.Equals(tp, typeParameter),
        INamedTypeSymbol named => named.TypeArguments.Any(t => ContainsTypeParameter(t, typeParameter)),
        IArrayTypeSymbol array => ContainsTypeParameter(array.ElementType, typeParameter),
        _ => false,
    };

    private static bool ContainsAnyTypeParameter(ITypeSymbol type) => type switch
    {
        ITypeParameterSymbol => true,
        INamedTypeSymbol named => named.TypeArguments.Any(ContainsAnyTypeParameter),
        IArrayTypeSymbol array => ContainsAnyTypeParameter(array.ElementType),
        _ => false,
    };
}
