using System.Collections.Immutable;
using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace IfItQuacks.Generator;

/// <summary>
/// Generates adapters and interceptors that let <c>[DuckTyped]</c> methods accept any type structurally matching their interface parameters.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class IfItQuacksGenerator : IIncrementalGenerator
{
    private const string DuckTypedAttributeName = "IfItQuacks.DuckTypedAttribute";
    private const string DuckShapeAttributeName = "IfItQuacks.DuckShapeAttribute`1";
    private const string DuckTypeName = "IfItQuacks.Duck";
    private const string DuckAsMethodName = "As";
    private const string DuckStubMethodName = "Stub";
    private const string DuckMergeMethodName = "Merge";
    private const string DuckToMethodName = "To";
    private const string GeneratedNamespace = "IfItQuacks.Generated";
    private const string InterceptorIndexPlaceholder = "__INDEX__";
    private const string EditorBrowsableNever = "[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]";
    private const int MaxFallbackVariantParameters = 4;
    private const string Header = "// <auto-generated/>\n#nullable enable\n";

    internal const string CallSitesTrackingName = "IfItQuacks.CallSites";
    internal const string MethodGroupsTrackingName = "IfItQuacks.MethodGroups";
    internal const string MappedShapesTrackingName = "IfItQuacks.MappedShapes";

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource("IfItQuacksAttributes.g.cs", SourceText.From(EmbeddedSources.Attributes, Encoding.UTF8)));

        var duckTypedMethods = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                DuckTypedAttributeName,
                predicate: static (node, _) => node is MethodDeclarationSyntax,
                transform: static (ctx, _) => AnalyzeDuckTypedMethod(ctx));

        context.RegisterSourceOutput(duckTypedMethods, static (spc, method) => EmitDuckTypedMethod(spc, method));

        var duckTypedNames = duckTypedMethods
            .Select(static (method, _) => method.Reference)
            .Collect()
            .Select(static (refs, _) => new EquatableArray<DuckMethodRef>(
                refs.Distinct().OrderBy(r => r.ContainingType, StringComparer.Ordinal).ThenBy(r => r.Name, StringComparer.Ordinal).ToImmutableArray()));

        var mappedShapes = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                DuckShapeAttributeName,
                predicate: static (node, _) => node is InterfaceDeclarationSyntax,
                transform: static (ctx, _) => AnalyzeMappedShape(ctx))
            .WithTrackingName(MappedShapesTrackingName);

        context.RegisterSourceOutput(mappedShapes, static (spc, shape) => EmitMappedShape(spc, shape));

        var callSites = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is InvocationExpressionSyntax invocation && GetInvokedName(invocation) is not null,
                transform: static (ctx, _) => (InvocationExpressionSyntax)ctx.Node)
            .Combine(duckTypedNames)
            .Where(static pair => GetInvokedName(pair.Left) is { } name &&
                                  (name is DuckAsMethodName or DuckStubMethodName or DuckMergeMethodName or DuckToMethodName ||
                                   pair.Right.Any(r => r.Name == name)))
            .Combine(context.CompilationProvider)
            .Select(static (pair, ct) => AnalyzeCallSite(pair.Left.Left, pair.Left.Right, pair.Right, ct))
            .WithTrackingName(CallSitesTrackingName);

        // A method group can't be intercepted, so a concrete overload is generated for the delegate it converts to.
        var methodGroups = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => AsMethodGroup(node) is not null,
                transform: static (ctx, _) => AsMethodGroup(ctx.Node)!)
            .Combine(duckTypedNames)
            .Where(static pair => pair.Right.Any(r => r.Name == GetMethodGroupName(pair.Left)))
            .Select(static (pair, _) => pair.Left)
            .Combine(context.CompilationProvider)
            .Select(static (pair, ct) => AnalyzeMethodGroup(pair.Left, pair.Right, ct))
            .WithTrackingName(MethodGroupsTrackingName);

        context.RegisterSourceOutput(callSites.Collect().Combine(methodGroups.Collect()),
            static (spc, sites) => EmitCallSites(spc, [.. sites.Left, .. sites.Right]));
    }

    private static DuckTypedMethodOutput AnalyzeDuckTypedMethod(GeneratorAttributeSyntaxContext ctx)
    {
        var method = (IMethodSymbol)ctx.TargetSymbol;
        var diagnostics = ImmutableArray.CreateBuilder<Diagnostic>();
        var isValid = ValidateDuckTypedMethod(method, ctx.TargetNode.GetLocation(), diagnostics);

        var fallback = isValid && !method.IsGenericMethod ? CreateFallbackOverload(method) : null;
        var reference = new DuckMethodRef(method.Name, MetadataName(method.ContainingType), isValid && method.IsExtensionMethod);
        return new DuckTypedMethodOutput(reference, fallback, new EquatableArray<Diagnostic>(diagnostics.ToImmutable()));
    }

    private static MappedShapeOutput AnalyzeMappedShape(GeneratorAttributeSyntaxContext ctx)
    {
        var target = (INamedTypeSymbol)ctx.TargetSymbol;
        var location = ctx.TargetNode.GetLocation();
        var diagnostics = ImmutableArray.CreateBuilder<Diagnostic>();

        var reason = FindUnsupportedMappedShapeTarget(target, ctx.TargetNode);
        if (reason is not null)
        {
            diagnostics.Add(Diagnostic.Create(Diagnostics.MappedShapeNotPartialInterface, location, target.Name, reason));
            return new MappedShapeOutput(null, new EquatableArray<Diagnostic>(diagnostics.ToImmutable()));
        }

        var options = ctx.Attributes
            .Select(MappedShapeEmitter.ReadOptions)
            .Where(o => o is not null)
            .Select(o => o!)
            .ToImmutableArray();

        if (options.IsEmpty)
            return new MappedShapeOutput(null, default);

        var members = MappedShapeEmitter.Emit(target, options, diagnostics, location);
        if (members is null)
            return new MappedShapeOutput(null, new EquatableArray<Diagnostic>(diagnostics.ToImmutable()));

        var file = new GeneratedFile(
            $"IfItQuacks.Shape.{SanitizeHintName(target.ToDisplayString())}.g.cs",
            Header + TypeWrapper.WrapInContainingScope(target, members.TrimEnd('\n', '\r')));
        return new MappedShapeOutput(file, default);
    }

    // The generated members go into a second declaration of the interface, so it and every type around it has to be partial.
    private static string? FindUnsupportedMappedShapeTarget(INamedTypeSymbol target, SyntaxNode node)
    {
        if (node is InterfaceDeclarationSyntax declaration && !declaration.Modifiers.Any(SyntaxKind.PartialKeyword))
            return "it is not declared 'partial'";

        if (IsInGenericType(target))
            return "its containing type is generic";

        if (IsInFileLocalType(target))
            return "its containing type is file-local";

        var enclosingNotPartial = Utilities.EnclosingTypes(target).Skip(1).Any(t => t.DeclaringSyntaxReferences
            .Select(r => r.GetSyntax())
            .OfType<TypeDeclarationSyntax>()
            .Any(d => !d.Modifiers.Any(SyntaxKind.PartialKeyword)));

        return enclosingNotPartial ? "one of its containing types is not declared 'partial'" : null;
    }

    private static void EmitMappedShape(SourceProductionContext context, MappedShapeOutput shape)
    {
        foreach (var diagnostic in shape.Diagnostics)
            context.ReportDiagnostic(diagnostic);

        if (shape.File is { } file)
            context.AddSource(file.Name, SourceText.From(file.Source, Encoding.UTF8));
    }

    private static bool ValidateDuckTypedMethod(IMethodSymbol method, Location location, ImmutableArray<Diagnostic>.Builder? diagnostics)
    {
        if (method.ContainingType.DeclaringSyntaxReferences
                .Select(r => r.GetSyntax())
                .OfType<TypeDeclarationSyntax>()
                .Any(t => !t.Modifiers.Any(SyntaxKind.PartialKeyword)))
        {
            diagnostics?.Add(Diagnostic.Create(Diagnostics.ContainingTypeNotPartial, location,
                method.Name, method.ContainingType.Name));
        }

        var unsupportedReason = method switch
        {
            _ when IsInGenericType(method.ContainingType) => "its containing type is generic",
            _ when method.ContainingType.TypeKind == TypeKind.Interface => "its containing type is an interface",
            // A file-local type can't be extended by a partial declaration in the generated file.
            _ when IsInFileLocalType(method.ContainingType) => "its containing type is file-local",
            _ => null,
        };
        if (unsupportedReason is not null)
        {
            diagnostics?.Add(Diagnostic.Create(Diagnostics.UnsupportedSignature, location, method.Name, unsupportedReason));
            return false;
        }

        var duckParameters = GetDuckParameters(method);
        var constraintTypeParameters = GetConstraintTypeParameters(method);
        if (!constraintTypeParameters.IsEmpty)
            return ValidateConstraintMethod(method, constraintTypeParameters, location, diagnostics);

        if (duckParameters.IsEmpty)
        {
            diagnostics?.Add(Diagnostic.Create(Diagnostics.ParameterNotShape, location, method.Name));
            return false;
        }

        var unusedTypeParameter = method.TypeParameters.FirstOrDefault(tp => !duckParameters.Any(p => ContainsTypeParameter(p.Type, tp)));
        if (unusedTypeParameter is not null)
        {
            diagnostics?.Add(Diagnostic.Create(Diagnostics.UnsupportedSignature, location, method.Name,
                $"its type parameter '{unusedTypeParameter.Name}' is not used by an interface parameter"));
            return false;
        }

        if (method.ContainingType.GetMembers(method.Name).OfType<IMethodSymbol>().Count(IsDuckTyped) > 1)
        {
            diagnostics?.Add(Diagnostic.Create(Diagnostics.UnsupportedSignature, location, method.Name,
                "it is overloaded (only one [DuckTyped] method per name is supported)"));
            return false;
        }

        return true;
    }

    // A duck-typed constraint, e.g. 'where T : IAddable<T>', lets static abstract members and operators be matched structurally.
    private static ImmutableArray<ITypeParameterSymbol> GetConstraintTypeParameters(IMethodSymbol method) =>
        method.TypeParameters
            .Where(tp => tp.ConstraintTypes.Length == 1 &&
                         tp.ConstraintTypes[0] is INamedTypeSymbol { TypeKind: TypeKind.Interface } &&
                         method.Parameters.Any(p => p is { RefKind: RefKind.None } && SymbolEqualityComparer.Default.Equals(p.Type, tp)))
            .ToImmutableArray();

    private static bool ValidateConstraintMethod(IMethodSymbol method,
        ImmutableArray<ITypeParameterSymbol> constraintTypeParameters, Location location, ImmutableArray<Diagnostic>.Builder? diagnostics)
    {
        if (method.TypeParameters.Length == constraintTypeParameters.Length)
            return true;

        diagnostics?.Add(Diagnostic.Create(Diagnostics.UnsupportedSignature, location, method.Name,
            "not all of its type parameters have a single interface constraint used by a parameter"));
        return false;
    }

    private static string MetadataName(INamedTypeSymbol type)
    {
        var nested = Utilities.EnclosingTypes(type).Reverse().Select(t => t.MetadataName);
        var name = string.Join("+", nested);
        return type.ContainingNamespace.IsGlobalNamespace ? name : type.ContainingNamespace.ToDisplayString() + "." + name;
    }

    // 'person.Describe()' binds to nothing until the generated extension exists, so the [DuckTyped] method is looked up by name.
    private static IMethodSymbol? FindExtensionCandidate(InvocationExpressionSyntax invocation,
        EquatableArray<DuckMethodRef> duckMethods, Compilation compilation)
    {
        if (GetReceiverExpression(invocation) is null || GetInvokedName(invocation) is not { } name)
            return null;

        return duckMethods
            .Where(r => r.IsExtension && r.Name == name)
            .Select(r => compilation.GetTypeByMetadataName(r.ContainingType)?.GetMembers(name).OfType<IMethodSymbol>()
                .FirstOrDefault(m => m.IsExtensionMethod && IsDuckTyped(m)))
            .FirstOrDefault(m => m is not null);
    }

    private static CallSiteOutput? AnalyzeCallSite(InvocationExpressionSyntax invocation,
        EquatableArray<DuckMethodRef> duckMethods, Compilation compilation, CancellationToken ct)
    {
        if (!compilation.ContainsSyntaxTree(invocation.SyntaxTree))
            return null;

        var semanticModel = compilation.GetSemanticModel(invocation.SyntaxTree);
        var symbolInfo = semanticModel.GetSymbolInfo(invocation, ct);
        var candidates = symbolInfo.Symbol is IMethodSymbol s
            ? [s]
            : symbolInfo.CandidateSymbols.OfType<IMethodSymbol>().ToImmutableArray();

        var conversion = candidates.FirstOrDefault(c => IsDuckConversion(c, compilation));
        if (conversion is not null)
        {
            return conversion.Name switch
            {
                DuckStubMethodName => AnalyzeDuckStubCall(semanticModel, invocation, conversion, ct),
                DuckMergeMethodName => AnalyzeDuckMergeCall(semanticModel, invocation, conversion, ct),
                DuckToMethodName => AnalyzeDuckToCall(semanticModel, invocation, conversion, ct),
                _ => AnalyzeDuckAsCall(semanticModel, invocation, conversion, ct),
            };
        }

        var candidate = candidates
            .FirstOrDefault(c => (c.ReducedFrom ?? c).OriginalDefinition is { DeclaringSyntaxReferences.Length: > 0 } d && IsDuckTyped(d));
        var isReduced = candidate?.MethodKind == MethodKind.ReducedExtension;
        if (candidate is null && FindExtensionCandidate(invocation, duckMethods, compilation) is { } extension)
        {
            candidate = extension;
            isReduced = true;
        }

        var duckMethod = (candidate?.ReducedFrom ?? candidate)?.OriginalDefinition;
        if (duckMethod is null || !ValidateDuckTypedMethod(duckMethod, Location.None, diagnostics: null))
            return null;

        // 'person.Describe(x)' passes the receiver as the extension method's first parameter, which the argument list doesn't contain.
        var arguments = MapArguments(invocation.ArgumentList, duckMethod, isReduced);
        if (arguments is null)
            return null;

        if (isReduced)
        {
            if (GetReceiverExpression(invocation) is not { } receiver)
                return null;
            arguments[0] = receiver;
        }

        if (GetConstraintTypeParameters(duckMethod) is { IsEmpty: false } constraintTypeParameters)
            return AnalyzeConstraintCall(semanticModel, duckMethod, constraintTypeParameters, arguments, compilation, ct);

        var duckArguments = new List<(IParameterSymbol Parameter, ExpressionSyntax Expression, ITypeSymbol ConcreteType)>();
        var passedThrough = new Dictionary<int, (ITypeSymbol ConcreteType, string? AdapterName)>();
        var duckParameters = GetDuckParameters(duckMethod);
        foreach (var parameter in duckParameters)
        {
            if (!arguments.TryGetValue(parameter.Ordinal, out var expression))
            {
                if (duckMethod.IsGenericMethod)
                    return null;
                continue;
            }

            // Omitted arguments, null/default literals and values already typed as the interface bind to a fallback variant keeping that parameter as is.
            var argumentType = GetArgumentType(semanticModel, expression, compilation, ct);
            if (!duckMethod.IsGenericMethod && duckParameters.Length <= MaxFallbackVariantParameters &&
                (argumentType is null || SymbolEqualityComparer.Default.Equals(argumentType, parameter.Type)))
                continue;

            if (argumentType is IArrayTypeSymbol array && !duckMethod.IsGenericMethod &&
                compilation.ClassifyCommonConversion(array, parameter.Type) is { IsImplicit: true, IsUserDefined: false })
            {
                passedThrough[parameter.Ordinal] = (array, null);
                continue;
            }

            if (argumentType is null || argumentType.TypeKind == TypeKind.Error ||
                (duckMethod.IsGenericMethod && ContainsAnyTypeParameter(argumentType)))
                return null;

            // Only a sequence can be adapted without being a named type, e.g. a Person[] passed as IEnumerable<INamed>.
            if (argumentType is not INamedTypeSymbol &&
                (duckMethod.IsGenericMethod || parameter.Type is not INamedTypeSymbol shapeType ||
                 SequenceAdapterEmitter.TryMatch(shapeType, argumentType, compilation) is null))
                return null;

            duckArguments.Add((parameter, expression, argumentType));
        }

        if (duckArguments.Count == 0 && passedThrough.Count == 0)
            return null;

        if (IsBaseCall(invocation))
        {
            return DiagnosticsOnly([Diagnostic.Create(Diagnostics.UnsupportedCall, invocation.GetLocation(), duckMethod.Name,
                "a 'base' call is not virtual, which neither an interceptor nor the fallback overload can reproduce")]);
        }

        var diagnostics = ImmutableArray.CreateBuilder<Diagnostic>();
        var targetMethod = duckMethod;
        if (duckMethod.IsGenericMethod)
        {
            foreach (var (parameter, expression, argumentType) in duckArguments)
            {
                var concreteType = (INamedTypeSymbol)argumentType;
                var shape = (INamedTypeSymbol)parameter.Type;
                if (!concreteType.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i.OriginalDefinition, shape.OriginalDefinition)) &&
                    FindUnsupportedMemberDiagnostic(expression, shape) is { } unsupported)
                    diagnostics.Add(unsupported);
                else if (concreteType.IsAnonymousType)
                    diagnostics.Add(Diagnostic.Create(Diagnostics.ShapeMismatch, expression.GetLocation(), concreteType.ToDisplayString(),
                        parameter.Type.ToDisplayString(), "anonymous types are not supported by generic [DuckTyped] methods"));
            }
            if (diagnostics.Count > 0)
                return DiagnosticsOnly(diagnostics);

            var constructed = TypeArgumentInference.TryConstruct(duckMethod,
                duckArguments.Select(a => (a.Parameter, (INamedTypeSymbol)a.ConcreteType)));
            if (constructed is null)
            {
                var failing = duckArguments.FirstOrDefault(a =>
                    ShapeMatcher.FindMismatch((INamedTypeSymbol)a.Parameter.Type, (INamedTypeSymbol)a.ConcreteType, compilation) is not null);
                if (failing.Parameter is null)
                    failing = duckArguments[0];
                diagnostics.Add(Diagnostic.Create(Diagnostics.ShapeMismatch, failing.Expression.GetLocation(),
                    failing.ConcreteType.ToDisplayString(), failing.Parameter.Type.ToDisplayString(),
                    ShapeMatcher.FindMismatch((INamedTypeSymbol)failing.Parameter.Type, (INamedTypeSymbol)failing.ConcreteType, compilation)
                    ?? $"type arguments for '{duckMethod.Name}' could not be inferred"));
                return DiagnosticsOnly(diagnostics);
            }
            targetMethod = constructed;
        }

        var adapters = ImmutableArray.CreateBuilder<GeneratedFile>();
        var resolved = new Dictionary<int, (ITypeSymbol ConcreteType, string? AdapterName)>(passedThrough);
        foreach (var (parameter, expression, concreteType) in duckArguments)
        {
            var shape = (INamedTypeSymbol)WithoutNullability(targetMethod.Parameters[parameter.Ordinal].Type);
            if (VerifyArgument(expression, shape, concreteType, compilation, out var implementsDirectly) is { } diagnostic)
            {
                diagnostics.Add(diagnostic);
                continue;
            }

            var adapter = implementsDirectly ? null : CreateAdapter(shape, concreteType, compilation);
            if (adapter is not null)
                adapters.AddRange(adapter.Files);
            resolved[parameter.Ordinal] = (concreteType, adapter?.Name);
        }

        if (diagnostics.Count > 0)
            return DiagnosticsOnly(diagnostics);

        if (duckMethod.IsGenericMethod)
        {
            return adapters.Count == 0
                ? null
                : new CallSiteOutput(null, new EquatableArray<GeneratedFile>(adapters.ToImmutable()),
                    CreateDuckOverload(duckMethod, targetMethod, resolved), default);
        }

        var location = semanticModel.GetInterceptableLocation(invocation, ct);
        if (location is null)
            return null;

        return new CallSiteOutput(CreateInterceptor(location, duckMethod, resolved, isReduced),
            new EquatableArray<GeneratedFile>(adapters.ToImmutable()), null, default);
    }

    // A name used as a value, e.g. 'Ops.Describe' in 'Func<Person, string> f = Ops.Describe;' or 'items.Select(Ops.Describe)'.
    private static ExpressionSyntax? AsMethodGroup(SyntaxNode node)
    {
        if (node is not SimpleNameSyntax name || name.Parent is null)
            return null;

        var expression = name.Parent is MemberAccessExpressionSyntax member && member.Name == name ? (ExpressionSyntax)member : name;
        if (expression.Parent is null)
            return null;

        return expression.Parent switch
        {
            InvocationExpressionSyntax invocation when invocation.Expression == expression => null,
            MemberAccessExpressionSyntax or MemberBindingExpressionSyntax or NameSyntax or TypeSyntax => null,
            _ => expression,
        };
    }

    private static string GetMethodGroupName(ExpressionSyntax expression) => expression switch
    {
        MemberAccessExpressionSyntax member => member.Name.Identifier.Text,
        SimpleNameSyntax name => name.Identifier.Text,
        _ => string.Empty,
    };

    private static CallSiteOutput? AnalyzeMethodGroup(ExpressionSyntax expression, Compilation compilation, CancellationToken ct)
    {
        if (!compilation.ContainsSyntaxTree(expression.SyntaxTree))
            return null;

        var semanticModel = compilation.GetSemanticModel(expression.SyntaxTree);
        var symbolInfo = semanticModel.GetSymbolInfo(expression, ct);
        var duckMethod = (symbolInfo.Symbol as IMethodSymbol ?? symbolInfo.CandidateSymbols.OfType<IMethodSymbol>().FirstOrDefault())?.OriginalDefinition;
        if (duckMethod is null || duckMethod.IsGenericMethod || duckMethod.DeclaringSyntaxReferences.Length == 0 ||
            !IsDuckTyped(duckMethod) || !ValidateDuckTypedMethod(duckMethod, Location.None, diagnostics: null))
            return null;

        if (semanticModel.GetTypeInfo(expression, ct).ConvertedType is not INamedTypeSymbol { DelegateInvokeMethod: { } invoke } ||
            invoke.Parameters.Length != duckMethod.Parameters.Length)
            return null;

        var adapters = ImmutableArray.CreateBuilder<GeneratedFile>();
        var resolved = new Dictionary<int, (ITypeSymbol ConcreteType, string? AdapterName)>();
        foreach (var parameter in GetDuckParameters(duckMethod))
        {
            if (invoke.Parameters[parameter.Ordinal].Type is not INamedTypeSymbol concreteType ||
                concreteType.TypeKind == TypeKind.Error || ContainsAnyTypeParameter(concreteType) ||
                SymbolEqualityComparer.Default.Equals(concreteType, parameter.Type))
                continue;

            var shape = (INamedTypeSymbol)WithoutNullability(parameter.Type);
            if (VerifyArgument(expression, shape, concreteType, compilation, out var implementsDirectly) is not null || implementsDirectly)
                continue;

            var adapter = CreateAdapter(shape, concreteType, compilation);
            adapters.AddRange(adapter.Files);
            resolved[parameter.Ordinal] = (concreteType, adapter.Name);
        }

        return resolved.Count == 0
            ? null
            : new CallSiteOutput(null, new EquatableArray<GeneratedFile>(adapters.ToImmutable()),
                CreateDuckOverload(duckMethod, duckMethod, resolved), default);
    }

    private static CallSiteOutput? AnalyzeConstraintCall(SemanticModel semanticModel, IMethodSymbol duckMethod,
        ImmutableArray<ITypeParameterSymbol> constraintTypeParameters, Dictionary<int, ExpressionSyntax> arguments,
        Compilation compilation, CancellationToken ct)
    {
        var diagnostics = ImmutableArray.CreateBuilder<Diagnostic>();
        var adapters = ImmutableArray.CreateBuilder<GeneratedFile>();
        var bindings = new Dictionary<ITypeParameterSymbol, (INamedTypeSymbol ConcreteType, string? AdapterName)>(SymbolEqualityComparer.Default);

        foreach (var typeParameter in constraintTypeParameters)
        {
            var boundParameters = duckMethod.Parameters
                .Where(p => SymbolEqualityComparer.Default.Equals(p.Type, typeParameter))
                .ToImmutableArray();

            var argumentTypes = boundParameters
                .Select(p => arguments.TryGetValue(p.Ordinal, out var expression)
                    ? (Expression: expression, Type: GetArgumentType(semanticModel, expression, compilation, ct))
                    : default)
                .ToImmutableArray();

            if (argumentTypes.Any(a => a.Type is not INamedTypeSymbol { TypeKind: not TypeKind.Error } type || ContainsAnyTypeParameter(type)) ||
                argumentTypes.Select(a => a.Type).Distinct(SymbolEqualityComparer.Default).Count() != 1)
                return null;

            var concreteType = (INamedTypeSymbol)argumentTypes[0].Type!;
            var shape = (INamedTypeSymbol)SubstituteTypeParameter(typeParameter.ConstraintTypes[0], typeParameter, concreteType);

            // A type satisfying the constraint itself needs no adapter; the call compiles as it is.
            if (concreteType.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i, shape)))
            {
                bindings[typeParameter] = (concreteType, null);
                continue;
            }

            var location = argumentTypes[0].Expression.GetLocation();
            // The overload names the argument's type in its signature, which an anonymous type has no name for.
            if (concreteType.IsAnonymousType)
            {
                diagnostics.Add(Diagnostic.Create(Diagnostics.ShapeMismatch, location, concreteType.ToDisplayString(),
                    shape.ToDisplayString(), "anonymous types are not supported by duck-typed constraints"));
                continue;
            }

            if (StaticShapeMatcher.FindUnsupportedMember(shape) is { } unsupportedStatic)
            {
                diagnostics.Add(Diagnostic.Create(Diagnostics.UnsupportedShapeMember, location, shape.ToDisplayString(),
                    unsupportedStatic.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat)));
                continue;
            }

            // Static abstract members are the point here, but an instance member using the self type can't be forwarded.
            if (ShapeMatcher.GetShapeMembers(shape)
                    .FirstOrDefault(m => m is IMethodSymbol { IsGenericMethod: true } || UsesSelfType(m, concreteType)) is { } unsupportedInstance)
            {
                diagnostics.Add(Diagnostic.Create(Diagnostics.UnsupportedShapeMember, location, shape.ToDisplayString(),
                    unsupportedInstance.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat)));
                continue;
            }

            var mismatch = StaticShapeMatcher.FindMismatch(shape, concreteType, compilation) ??
                           ShapeMatcher.FindMismatch(shape, concreteType, compilation);
            if (mismatch is not null)
            {
                diagnostics.Add(Diagnostic.Create(Diagnostics.ShapeMismatch, location, concreteType.ToDisplayString(),
                    shape.ToDisplayString(), mismatch));
                continue;
            }

            if (GetUnsupportedStructKind(concreteType, implementsDirectly: false) is { } unsupportedStruct)
            {
                diagnostics.Add(Diagnostic.Create(Diagnostics.UnsupportedStructArgument, location, concreteType.ToDisplayString(),
                    shape.ToDisplayString(), unsupportedStruct));
                continue;
            }

            var adapterName = AdapterEmitter.GetAdapterName(shape, concreteType);
            adapters.Add(new GeneratedFile(adapterName, SelfShapeAdapterEmitter.Emit(shape, concreteType, adapterName, compilation)));
            bindings[typeParameter] = (concreteType, adapterName);
        }

        // Interface parameters next to the constraints keep the regular adapter, boxed as the interface.
        var shapeBindings = new Dictionary<int, (INamedTypeSymbol ConcreteType, string AdapterName)>();
        foreach (var parameter in GetDuckParameters(duckMethod))
        {
            if (!arguments.TryGetValue(parameter.Ordinal, out var expression))
                continue;

            var argumentType = GetArgumentType(semanticModel, expression, compilation, ct);
            // A null literal, an omitted argument or a value already typed as the interface needs no adapter.
            if (argumentType is null || SymbolEqualityComparer.Default.Equals(argumentType, parameter.Type) ||
                ContainsErrorType(argumentType) || ContainsAnyTypeParameter(argumentType))
                continue;

            var shape = (INamedTypeSymbol)parameter.Type;
            if (VerifyArgument(expression, shape, argumentType, compilation, out var implementsDirectly) is { } diagnostic)
            {
                diagnostics.Add(diagnostic);
                continue;
            }

            if (implementsDirectly)
                continue;

            if (argumentType is not INamedTypeSymbol { IsAnonymousType: false } named)
            {
                diagnostics.Add(Diagnostic.Create(Diagnostics.ShapeMismatch, expression.GetLocation(), argumentType.ToDisplayString(),
                    shape.ToDisplayString(), "anonymous types and sequences are not supported next to duck-typed constraints"));
                continue;
            }

            var adapter = CreateAdapter(shape, named, compilation);
            adapters.AddRange(adapter.Files);
            shapeBindings[parameter.Ordinal] = (named, adapter.Name);
        }

        if (diagnostics.Count > 0)
            return DiagnosticsOnly(diagnostics);

        if (bindings.Count != constraintTypeParameters.Length ||
            (bindings.Values.All(b => b.AdapterName is null) && shapeBindings.Count == 0))
            return null;

        var overload = CreateConstraintOverload(duckMethod, bindings, shapeBindings);
        return overload is null
            ? null
            : new CallSiteOutput(null, new EquatableArray<GeneratedFile>(adapters.ToImmutable()), overload, default);
    }

    // Only members whose signature is free of the self type can be forwarded by the generated adapter.
    private static bool UsesSelfType(ISymbol member, INamedTypeSymbol self) => member switch
    {
        IMethodSymbol method => Mentions(method.ReturnType, self) || method.Parameters.Any(p => Mentions(p.Type, self)),
        IPropertySymbol property => Mentions(property.Type, self) || property.Parameters.Any(p => Mentions(p.Type, self)),
        IEventSymbol @event => Mentions(@event.Type, self),
        _ => false,
    };

    private static bool Mentions(ITypeSymbol type, INamedTypeSymbol self) =>
        Utilities.ContainsType(type, t => SymbolEqualityComparer.Default.Equals(t, self));

    private static ITypeSymbol SubstituteTypeParameter(ITypeSymbol type, ITypeParameterSymbol typeParameter, ITypeSymbol replacement) => type switch
    {
        ITypeParameterSymbol tp when SymbolEqualityComparer.Default.Equals(tp, typeParameter) => replacement,
        INamedTypeSymbol { IsGenericType: true } named =>
            named.OriginalDefinition.Construct([.. named.TypeArguments.Select(t => SubstituteTypeParameter(t, typeParameter, replacement))]),
        _ => type,
    };

    private static OverloadMember? CreateConstraintOverload(IMethodSymbol method,
        Dictionary<ITypeParameterSymbol, (INamedTypeSymbol ConcreteType, string? AdapterName)> bindings,
        Dictionary<int, (INamedTypeSymbol ConcreteType, string AdapterName)> shapeBindings)
    {
        string? Bound(ITypeSymbol type) =>
            type is ITypeParameterSymbol tp && bindings.TryGetValue(tp, out var binding) ? binding.ConcreteType.ToDisplayString() : null;

        string ParameterType(IParameterSymbol p) =>
            shapeBindings.TryGetValue(p.Ordinal, out var shapeBinding)
                ? shapeBinding.ConcreteType.ToDisplayString()
                : Bound(p.Type) ?? p.Type.ToDisplayString();

        if (method.Parameters.Any(p => Bound(p.Type) is null && ContainsAnyTypeParameter(p.Type)) ||
            (Bound(method.ReturnType) is null && ContainsAnyTypeParameter(method.ReturnType)))
            return null;

        var parameters = string.Join(", ", method.Parameters.Select((p, i) =>
            (method.IsExtensionMethod && i == 0 ? "this " : "") +
            Utilities.Parameter(p, ParameterType(p)) + (shapeBindings.ContainsKey(p.Ordinal) ? "" : Utilities.DefaultValue(p))));

        var arguments = string.Join(", ", method.Parameters.Select(p =>
        {
            if (shapeBindings.TryGetValue(p.Ordinal, out var shapeBinding))
            {
                // The cast keeps overload resolution on the user's method instead of the generated overload.
                return $"({p.Type.ToDisplayString()})(new global::{GeneratedNamespace}.{shapeBinding.AdapterName}({Utilities.Identifier(p.Name)}))";
            }

            return p.Type is ITypeParameterSymbol tp && bindings.TryGetValue(tp, out var binding) && binding.AdapterName is not null
                ? $"new global::{GeneratedNamespace}.{binding.AdapterName}({Utilities.Identifier(p.Name)})"
                : Utilities.Argument(p);
        }));

        var typeArguments = string.Join(", ", method.TypeParameters.Select(tp =>
            bindings[tp].AdapterName is { } adapter ? $"global::{GeneratedNamespace}.{adapter}" : bindings[tp].ConcreteType.ToDisplayString()));

        var returnType = Bound(method.ReturnType) ?? method.ReturnType.ToDisplayString();
        var call = $"{method.Name}<{typeArguments}>({arguments})";

        // A method returning the constrained type parameter returns an adapter, which converts back to the argument's type.
        var body = call;
        if (!method.ReturnsVoid && method.ReturnType is ITypeParameterSymbol returnedParameter &&
            bindings.TryGetValue(returnedParameter, out var returnBinding) && returnBinding.AdapterName is not null)
            body = $"({returnBinding.ConcreteType.ToDisplayString()})({call})";

        var accessibility = OverloadAccessibility(method,
            bindings.Values.Select(b => b.ConcreteType).Concat(shapeBindings.Values.Select(b => b.ConcreteType)));

        var member =
            $"{EditorBrowsableNever} {accessibility} {(method.IsStatic ? "static " : "")}{returnType} {method.Name}({parameters}) => {body};";

        return CreateOverloadMember(method, member);
    }

    private static CallSiteOutput? AnalyzeDuckStubCall(SemanticModel semanticModel, InvocationExpressionSyntax invocation,
        IMethodSymbol stubCall, CancellationToken ct)
    {
        if (GetConversionShape(stubCall) is not { } shape)
        {
            return DiagnosticsOnly([Diagnostic.Create(Diagnostics.ConversionTargetNotShape, invocation.GetLocation(),
                DuckStubMethodName, stubCall.TypeArguments[0].ToDisplayString())]);
        }

        if (ContainsAnyTypeParameter(shape))
            return null;

        var compilation = semanticModel.Compilation;
        // A stub implements what is missing, but it can't invent an instance for a static abstract member.
        if (ShapeMatcher.FindUnsupportedMember(shape, allowGenericMethods: true) is { } unsupported)
        {
            return DiagnosticsOnly([Diagnostic.Create(Diagnostics.UnsupportedShapeMember, invocation.GetLocation(),
                shape.ToDisplayString(), unsupported.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat))]);
        }

        if (invocation.ArgumentList.Arguments.Count == 0)
            return CreateStubCallSite(semanticModel, invocation, shape, concreteType: null, ct);

        if (invocation.ArgumentList.Arguments.Count == 1)
        {
            var argExpr = invocation.ArgumentList.Arguments[0].Expression;
            if (GetArgumentType(semanticModel, argExpr, compilation, ct) is not INamedTypeSymbol argumentType ||
                argumentType.TypeKind == TypeKind.Error || ContainsAnyTypeParameter(argumentType))
                return null;

            if (GetUnsupportedStructKind(argumentType, implementsDirectly: false) is { } unsupportedStruct)
            {
                return DiagnosticsOnly([Diagnostic.Create(Diagnostics.UnsupportedStructArgument, argExpr.GetLocation(),
                    argumentType.ToDisplayString(), shape.ToDisplayString(), unsupportedStruct)]);
            }

            if (FindUnnameableProperty(argumentType) is { } unnameable)
            {
                return DiagnosticsOnly([Diagnostic.Create(Diagnostics.ShapeMismatch, argExpr.GetLocation(),
                    argumentType.ToDisplayString(), shape.ToDisplayString(), unnameable)]);
            }

            if (ShapeMatcher.FindStubMismatch(shape, argumentType, compilation) is { } mismatch)
            {
                return DiagnosticsOnly([Diagnostic.Create(Diagnostics.ShapeMismatch, argExpr.GetLocation(),
                    argumentType.ToDisplayString(), shape.ToDisplayString(), mismatch)]);
            }

            return CreateStubCallSite(semanticModel, invocation, shape, argumentType, ct);
        }

        return null;
    }

    private static CallSiteOutput? CreateStubCallSite(SemanticModel semanticModel, InvocationExpressionSyntax invocation,
        INamedTypeSymbol shape, INamedTypeSymbol? concreteType, CancellationToken ct)
    {
        var location = semanticModel.GetInterceptableLocation(invocation, ct);
        if (location is null)
            return null;

        var adapterName = AdapterEmitter.GetStubAdapterName(shape, concreteType);
        var adapter = new GeneratedFile(adapterName, AdapterEmitter.EmitStub(shape, concreteType, adapterName, semanticModel.Compilation));

        var parameters = "";
        var argument = "";
        if (concreteType is not null)
        {
            parameters = "object value";
            argument = concreteType.IsAnonymousType ? "value" : $"({concreteType.ToDisplayString()})value";
        }

        var interceptor = ConversionInterceptor(location, $"global::{shape.ToDisplayString()}", parameters,
            $"new global::{GeneratedNamespace}.{adapterName}({argument})");

        return new CallSiteOutput(interceptor, new EquatableArray<GeneratedFile>([adapter]), null, default);
    }

    private static CallSiteOutput? AnalyzeDuckMergeCall(SemanticModel semanticModel, InvocationExpressionSyntax invocation,
        IMethodSymbol mergeCall, CancellationToken ct)
    {
        if (GetConversionShape(mergeCall) is not { } shape)
        {
            return DiagnosticsOnly([Diagnostic.Create(Diagnostics.ConversionTargetNotShape, invocation.GetLocation(),
                DuckMergeMethodName, mergeCall.TypeArguments[0].ToDisplayString())]);
        }

        var compilation = semanticModel.Compilation;
        if (ContainsAnyTypeParameter(shape) || invocation.ArgumentList.Arguments.Count != mergeCall.Parameters.Length)
            return null;

        if (FindUnsupportedMemberDiagnostic(invocation, shape) is { } unsupported)
            return DiagnosticsOnly([unsupported]);

        var sources = ImmutableArray.CreateBuilder<INamedTypeSymbol>();
        foreach (var argument in invocation.ArgumentList.Arguments)
        {
            if (GetArgumentType(semanticModel, argument.Expression, compilation, ct) is not INamedTypeSymbol sourceType ||
                sourceType.TypeKind == TypeKind.Error || ContainsAnyTypeParameter(sourceType))
                return null;

            if (GetUnsupportedStructKind(sourceType, implementsDirectly: false) is { } unsupportedStruct)
            {
                return DiagnosticsOnly([Diagnostic.Create(Diagnostics.UnsupportedStructArgument, argument.GetLocation(),
                    sourceType.ToDisplayString(), shape.ToDisplayString(), unsupportedStruct)]);
            }

            if (FindUnnameableProperty(sourceType) is { } unnameable)
            {
                return DiagnosticsOnly([Diagnostic.Create(Diagnostics.ShapeMismatch, argument.GetLocation(),
                    sourceType.ToDisplayString(), shape.ToDisplayString(), unnameable)]);
            }

            sources.Add(sourceType);
        }

        var merged = sources.ToImmutable();
        if (ShapeMatcher.GetShapeMembers(shape).Where(ShapeMatcher.IsRequired)
                .FirstOrDefault(m => AdapterEmitter.FindSource(merged, m, compilation) is null) is { } missing)
        {
            return DiagnosticsOnly([Diagnostic.Create(Diagnostics.ShapeMismatch, invocation.GetLocation(),
                string.Join("' + '", merged.Select(s => s.ToDisplayString())), shape.ToDisplayString(),
                $"no value provides '{missing.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat)}'")]);
        }

        var location = semanticModel.GetInterceptableLocation(invocation, ct);
        if (location is null)
            return null;

        var adapterName = AdapterEmitter.GetMergeAdapterName(shape, merged);
        var adapter = new GeneratedFile(adapterName, AdapterEmitter.EmitMerge(shape, merged, adapterName, compilation));

        var parameters = string.Join(", ", merged.Select((_, i) => $"object value{i}"));
        var arguments = string.Join(", ", merged.Select((s, i) => s.IsAnonymousType ? $"value{i}" : $"({s.ToDisplayString()})value{i}"));

        var interceptor = ConversionInterceptor(location, $"global::{shape.ToDisplayString()}", parameters,
            $"new global::{GeneratedNamespace}.{adapterName}({arguments})");

        return new CallSiteOutput(interceptor, new EquatableArray<GeneratedFile>([adapter]), null, default);
    }

    private static CallSiteOutput? AnalyzeDuckToCall(SemanticModel semanticModel, InvocationExpressionSyntax invocation,
        IMethodSymbol toCall, CancellationToken ct)
    {
        var compilation = semanticModel.Compilation;
        if (WithoutNullability(toCall.TypeArguments[0]) is not INamedTypeSymbol target || ContainsAnyTypeParameter(target))
            return null;

        if (invocation.ArgumentList.Arguments.Count != 1)
            return null;

        var argExpr = invocation.ArgumentList.Arguments[0].Expression;
        if (GetArgumentType(semanticModel, argExpr, compilation, ct) is not INamedTypeSymbol source ||
            source.TypeKind == TypeKind.Error || ContainsAnyTypeParameter(source))
            return null;

        if (FindUnnameableProperty(source) is { } unnameable)
        {
            return DiagnosticsOnly([Diagnostic.Create(Diagnostics.UnsupportedConversionTarget, invocation.GetLocation(),
                target.ToDisplayString(), source.ToDisplayString(), unnameable)]);
        }

        if (StructuralCopyEmitter.FindMismatch(target, source, compilation) is { } mismatch)
        {
            return DiagnosticsOnly([Diagnostic.Create(Diagnostics.UnsupportedConversionTarget, invocation.GetLocation(),
                target.ToDisplayString(), source.ToDisplayString(), mismatch)]);
        }

        var location = semanticModel.GetInterceptableLocation(invocation, ct);
        if (location is null)
            return null;

        var factoryName = StructuralCopyEmitter.GetFactoryName(target, source);
        var factory = new GeneratedFile(factoryName, StructuralCopyEmitter.Emit(target, source, factoryName, compilation));
        var argument = source.IsAnonymousType ? "value" : $"({source.ToDisplayString()})value";

        var interceptor = ConversionInterceptor(location, target.ToDisplayString(), "object value",
            $"global::{GeneratedNamespace}.{factoryName}.Create({argument})");

        return new CallSiteOutput(interceptor, new EquatableArray<GeneratedFile>([factory]), null, default);
    }

    private static string ConversionInterceptor(InterceptableLocation location, string returnType, string parameters, string body) =>
        $"        {location.GetInterceptsLocationAttributeSyntax()}\n" +
        $"        public static {returnType} Interceptor_{InterceptorIndexPlaceholder}({parameters}) => {body};\n";

    private static INamedTypeSymbol? GetConversionShape(IMethodSymbol conversion) =>
        WithoutNullability(conversion.TypeArguments[0]) is INamedTypeSymbol { TypeKind: TypeKind.Interface } shape ? shape : null;

    private static CallSiteOutput? AnalyzeDuckAsCall(SemanticModel semanticModel, InvocationExpressionSyntax invocation,
        IMethodSymbol duckAsCall, CancellationToken ct)
    {
        if (GetConversionShape(duckAsCall) is not { } shape)
        {
            return DiagnosticsOnly([Diagnostic.Create(Diagnostics.ConversionTargetNotShape, invocation.GetLocation(),
                DuckAsMethodName, duckAsCall.TypeArguments[0].ToDisplayString())]);
        }

        if (invocation.ArgumentList.Arguments.Count != 1 || ContainsAnyTypeParameter(shape))
            return null;

        var argExpr = invocation.ArgumentList.Arguments[0].Expression;
        if (GetArgumentType(semanticModel, argExpr, semanticModel.Compilation, ct) is not { } concreteType ||
            concreteType.TypeKind == TypeKind.Error || ContainsAnyTypeParameter(concreteType))
            return null;

        // Only a sequence can be adapted without being a named type, e.g. a Person[] converted to IEnumerable<INamed>.
        if (concreteType is not INamedTypeSymbol && SequenceAdapterEmitter.TryMatch(shape, concreteType, semanticModel.Compilation) is null)
            return null;

        if (VerifyArgument(argExpr, shape, concreteType, semanticModel.Compilation, out var implementsDirectly) is { } diagnostic)
            return DiagnosticsOnly([diagnostic]);

        var location = semanticModel.GetInterceptableLocation(invocation, ct);
        if (location is null)
            return null;

        var shapeTypeName = shape.ToDisplayString();
        var adapter = implementsDirectly ? null : CreateAdapter(shape, concreteType, semanticModel.Compilation);
        var argument = concreteType.IsAnonymousType ? "value" : $"({concreteType.ToDisplayString()})value";
        var result = adapter is null ? "value" : $"new global::{GeneratedNamespace}.{adapter.Name}({argument})";

        var interceptor = ConversionInterceptor(location, $"global::{shapeTypeName}", "object value", $"(global::{shapeTypeName})({result})");

        return new CallSiteOutput(interceptor,
            adapter is null ? default : new EquatableArray<GeneratedFile>(adapter.Files), null, default);
    }

    // The value an extension method's first parameter is bound to, e.g. 'person' in 'person.Describe()' or 'person?.Describe()'.
    private static ExpressionSyntax? GetReceiverExpression(InvocationExpressionSyntax invocation) => invocation.Expression switch
    {
        MemberAccessExpressionSyntax member => member.Expression,
        MemberBindingExpressionSyntax => invocation.Ancestors().OfType<ConditionalAccessExpressionSyntax>().FirstOrDefault()?.Expression,
        _ => null,
    };

    private static Dictionary<int, ExpressionSyntax>? MapArguments(ArgumentListSyntax argumentList, IMethodSymbol method, bool isReduced)
    {
        var offset = isReduced ? 1 : 0;
        var arguments = new Dictionary<int, ExpressionSyntax>();
        for (var i = 0; i < argumentList.Arguments.Count; i++)
        {
            var argument = argumentList.Arguments[i];
            IParameterSymbol? parameter;
            if (argument.NameColon is { } nameColon)
                parameter = method.Parameters.FirstOrDefault(p => p.Name == nameColon.Name.Identifier.ValueText);
            else if (i + offset < method.Parameters.Length)
                parameter = method.Parameters[i + offset];
            else
                parameter = method.Parameters.LastOrDefault(p => p.IsParams);

            if (parameter is null)
                return null;

            arguments[parameter.Ordinal] = argument.Expression;
        }
        return arguments;
    }

    // A lambda or method group has no type of its own, so its natural delegate type stands in for it.
    private static ITypeSymbol? GetArgumentType(SemanticModel semanticModel, ExpressionSyntax expression, Compilation compilation, CancellationToken ct)
    {
        var typeInfo = semanticModel.GetTypeInfo(expression, ct);
        // 'Person?' and 'Person' are the same type at runtime, so both share one adapter.
        if (typeInfo.Type is { } type)
            return WithoutNullability(type);

        if (typeInfo.ConvertedType is { TypeKind: TypeKind.Delegate } converted)
            return converted;

        return expression is AnonymousFunctionExpressionSyntax or SimpleNameSyntax or MemberAccessExpressionSyntax &&
               GetMethodSymbol(semanticModel.GetSymbolInfo(expression, ct)) is { } method
            ? NaturalDelegateType(method, compilation)
            : null;
    }

    private static IMethodSymbol? GetMethodSymbol(SymbolInfo symbolInfo) =>
        (symbolInfo.Symbol ?? symbolInfo.CandidateSymbols.SingleOrDefault()) as IMethodSymbol;

    // Mirrors the compiler's natural type for lambdas and method groups: Action for void, Func otherwise.
    private static INamedTypeSymbol? NaturalDelegateType(IMethodSymbol method, Compilation compilation)
    {
        if (method.IsGenericMethod || method.RefKind != RefKind.None || method.Parameters.Length > 15 ||
            method.Parameters.Any(p => p.RefKind != RefKind.None) ||
            ContainsErrorType(method.ReturnType) || method.Parameters.Any(p => ContainsErrorType(p.Type)))
            return null;

        var typeArguments = method.Parameters.Select(p => p.Type).ToList();
        if (method.ReturnsVoid)
        {
            var action = compilation.GetTypeByMetadataName(typeArguments.Count == 0 ? "System.Action" : $"System.Action`{typeArguments.Count}");
            return typeArguments.Count == 0 ? action : action?.Construct([.. typeArguments]);
        }

        typeArguments.Add(method.ReturnType);
        return compilation.GetTypeByMetadataName($"System.Func`{typeArguments.Count}")?.Construct([.. typeArguments]);
    }

    private static bool ContainsErrorType(ITypeSymbol type) =>
        Utilities.ContainsType(type, t => t.TypeKind == TypeKind.Error);

    private static Diagnostic? VerifyArgument(ExpressionSyntax argExpr, INamedTypeSymbol shape, ITypeSymbol argumentType,
        Compilation compilation, out bool implementsDirectly)
    {
        // Covers explicit implementations and variance (e.g. List<string> as IEnumerable<object>), which structural matching can't see.
        var conversion = compilation.ClassifyCommonConversion(argumentType, shape);
        implementsDirectly = conversion.IsImplicit && !conversion.IsUserDefined;
        if (implementsDirectly)
            return null;

        if (SequenceAdapterEmitter.TryMatch(shape, argumentType, compilation) is { } match)
            return VerifySequenceArgument(argExpr, shape, argumentType, match);

        if (FindUnsupportedMemberDiagnostic(argExpr, shape) is { } unsupported)
            return unsupported;

        if (argumentType is not INamedTypeSymbol concreteType)
        {
            return Diagnostic.Create(Diagnostics.ShapeMismatch, argExpr.GetLocation(),
                argumentType.ToDisplayString(), shape.ToDisplayString(), "only named types and sequences can be adapted");
        }

        var mismatch = ShapeMatcher.FindMismatch(shape, concreteType, compilation) ?? FindUnnameableProperty(concreteType);
        if (mismatch is not null)
        {
            return Diagnostic.Create(Diagnostics.ShapeMismatch, argExpr.GetLocation(),
                concreteType.ToDisplayString(), shape.ToDisplayString(), mismatch);
        }

        var unsupportedStructKind = GetUnsupportedStructKind(concreteType, implementsDirectly);
        return unsupportedStructKind is null
            ? null
            : Diagnostic.Create(Diagnostics.UnsupportedStructArgument, argExpr.GetLocation(),
                concreteType.ToDisplayString(), shape.ToDisplayString(), unsupportedStructKind);
    }

    // A sequence is adapted element by element, so it is the element type that has to be adaptable.
    private static Diagnostic? VerifySequenceArgument(ExpressionSyntax argExpr, INamedTypeSymbol shape, ITypeSymbol argumentType,
        SequenceAdapterEmitter.SequenceMatch match)
    {
        if (FindUnsupportedMemberDiagnostic(argExpr, match.ElementShape) is { } unsupported)
            return unsupported;

        if (GetUnsupportedStructKind(match.SourceElement, implementsDirectly: false) is { } unsupportedElement)
        {
            return Diagnostic.Create(Diagnostics.UnsupportedStructArgument, argExpr.GetLocation(),
                match.SourceElement.ToDisplayString(), match.ElementShape.ToDisplayString(), unsupportedElement);
        }

        return GetUnsupportedStructKind(argumentType, implementsDirectly: false) is { } unsupportedStruct
            ? Diagnostic.Create(Diagnostics.UnsupportedStructArgument, argExpr.GetLocation(),
                argumentType.ToDisplayString(), shape.ToDisplayString(), unsupportedStruct)
            : null;
    }

    private static string? FindUnnameableProperty(INamedTypeSymbol type) =>
        type.IsAnonymousType && AdapterEmitter.FindUnnameableProperty(type) is { } property
            ? $"property '{property}' has a type that contains an anonymous type"
            : null;

    private static Diagnostic? FindUnsupportedMemberDiagnostic(ExpressionSyntax argExpr, INamedTypeSymbol shape) =>
        ShapeMatcher.FindUnsupportedMember(shape) is { } member
            ? Diagnostic.Create(Diagnostics.UnsupportedShapeMember, argExpr.GetLocation(), shape.ToDisplayString(),
                member.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat))
            : null;

    private static CallSiteOutput DiagnosticsOnly(IEnumerable<Diagnostic> diagnostics) =>
        new(null, default, null, new EquatableArray<Diagnostic>(diagnostics.ToImmutableArray()));

    private static AdapterSet CreateAdapter(INamedTypeSymbol shape, ITypeSymbol concreteType, Compilation compilation)
    {
        if (SequenceAdapterEmitter.TryMatch(shape, concreteType, compilation) is { } match)
        {
            var elementName = AdapterEmitter.GetAdapterName(match.ElementShape, match.SourceElement);
            var element = new GeneratedFile(elementName, AdapterEmitter.Emit(match.ElementShape, match.SourceElement, elementName, compilation));
            var sequenceName = SequenceAdapterEmitter.GetAdapterName(shape, concreteType);
            var sequence = new GeneratedFile(sequenceName, SequenceAdapterEmitter.Emit(shape, concreteType, match, elementName, sequenceName));
            return new AdapterSet(sequenceName, [sequence, element]);
        }

        var named = (INamedTypeSymbol)concreteType;
        var name = AdapterEmitter.GetAdapterName(shape, named);
        return new AdapterSet(name, [new GeneratedFile(name, AdapterEmitter.Emit(shape, named, name, compilation))]);
    }

    private static ImmutableArray<IParameterSymbol> GetDuckParameters(IMethodSymbol method) =>
        method.Parameters
            .Where(p => p is { RefKind: RefKind.None, Type.TypeKind: TypeKind.Interface })
            .ToImmutableArray();

    private static bool IsDuckTyped(IMethodSymbol method) =>
        method.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == DuckTypedAttributeName);

    private static bool IsDuckConversion(IMethodSymbol method, Compilation compilation) =>
        method.Name is DuckAsMethodName or DuckStubMethodName or DuckMergeMethodName or DuckToMethodName &&
        method.TypeArguments.Length == 1 &&
        method.ContainingType.ToDisplayString() == DuckTypeName &&
        SymbolEqualityComparer.Default.Equals(method.ContainingAssembly, compilation.Assembly);

    private static bool IsInGenericType(INamedTypeSymbol type) => Utilities.EnclosingTypes(type).Any(t => t.IsGenericType);

    private static bool IsInFileLocalType(INamedTypeSymbol type) => Utilities.EnclosingTypes(type).Any(t => t.IsFileLocal);

    // A struct implementing the shape is boxed by the compiler itself, so only adapter-wrapped mutable structs would silently lose mutations.
    private static string? GetUnsupportedStructKind(ITypeSymbol type, bool implementsDirectly)
    {
        if (type.IsRefLikeType)
            return "ref structs cannot be converted to an interface";

        if (type.IsValueType && !type.IsReadOnly && !implementsDirectly)
            return "mutable structs are copied into an adapter, so mutations made through the shape would be lost";

        return null;
    }

    private static string? GetInvokedName(InvocationExpressionSyntax invocation) => invocation.Expression switch
    {
        SimpleNameSyntax name => name.Identifier.Text,
        MemberAccessExpressionSyntax member => member.Name.Identifier.Text,
        // 'receiver?.Greet(duck)': the conditional access holds the receiver, the invocation only the member name.
        MemberBindingExpressionSyntax binding => binding.Name.Identifier.Text,
        _ => null,
    };

    // 'base.Greet(duck)' calls the method non-virtually, which neither an interceptor nor the fallback overload can reproduce.
    private static bool IsBaseCall(InvocationExpressionSyntax invocation) =>
        invocation.Expression is MemberAccessExpressionSyntax { Expression: BaseExpressionSyntax };

    private static void EmitDuckTypedMethod(SourceProductionContext spc, DuckTypedMethodOutput method)
    {
        foreach (var diagnostic in method.Diagnostics)
            spc.ReportDiagnostic(diagnostic);

        if (method.Fallback is not null)
            spc.AddSource(method.Fallback.Name, SourceText.From(method.Fallback.Source, Encoding.UTF8));
    }

    private static void EmitCallSites(SourceProductionContext spc, ImmutableArray<CallSiteOutput?> sites)
    {
        var adapters = new SortedDictionary<string, string>(StringComparer.Ordinal);
        var overloadFiles = new SortedDictionary<string, (OverloadMember Template, SortedSet<string> Members)>(StringComparer.Ordinal);
        var interceptors = new StringBuilder();
        var interceptorCount = 0;

        foreach (var site in sites.OfType<CallSiteOutput>())
        {
            foreach (var diagnostic in site.Diagnostics)
                spc.ReportDiagnostic(diagnostic);

            foreach (var adapter in site.Adapters)
                adapters[adapter.Name] = adapter.Source;

            if (site.Overload is { } overload)
            {
                if (!overloadFiles.TryGetValue(overload.FileName, out var file))
                    overloadFiles[overload.FileName] = file = (overload, new SortedSet<string>(StringComparer.Ordinal));
                file.Members.Add(overload.Member);
            }

            if (site.Interceptor is not null)
            {
                interceptorCount++;
                interceptors.AppendLine();
                interceptors.Append(site.Interceptor.Replace(InterceptorIndexPlaceholder, interceptorCount.ToString(CultureInfo.InvariantCulture)));
            }
        }

        foreach (var (template, members) in overloadFiles.Values)
        {
            var indent = template.Prefix.Substring(template.Prefix.LastIndexOf('\n') + 1);
            var source = template.Prefix + string.Join("\n" + indent, members) + template.Suffix;
            spc.AddSource(template.FileName, SourceText.From(source, Encoding.UTF8));
        }

        if (interceptorCount > 0)
        {
            var sb = new StringBuilder(Header);
            sb.AppendLine(EmbeddedSources.InterceptsLocationAttributePolyfill);
            sb.AppendLine("namespace " + GeneratedNamespace);
            sb.AppendLine("{");
            sb.AppendLine("    file static class IfItQuacksInterceptors");
            sb.AppendLine("    {");
            sb.Append(interceptors);
            sb.AppendLine("    }");
            sb.AppendLine("}");
            spc.AddSource("IfItQuacks.Interceptors.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        if (adapters.Count > 0)
        {
            var sb = new StringBuilder(Header);
            sb.AppendLine("namespace " + GeneratedNamespace);
            sb.AppendLine("{");
            foreach (var adapter in adapters.Values)
                sb.Append(adapter);
            sb.AppendLine("}");
            spc.AddSource("IfItQuacks.Adapters.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }
    }

    private static GeneratedFile CreateFallbackOverload(IMethodSymbol method)
    {
        var duckParameters = GetDuckParameters(method);
        // One variant per subset of generic parameters, so null, default and omitted arguments can keep the interface type.
        var subsets = duckParameters.Length > MaxFallbackVariantParameters
            ? [duckParameters]
            : Enumerable.Range(1, (1 << duckParameters.Length) - 1)
                .Select(mask => duckParameters.Where((_, i) => (mask & (1 << i)) != 0).ToImmutableArray());

        var methodSource = string.Join("\n\n", subsets.Select(subset => CreateFallbackVariant(method, subset)));
        if (NeedsForwarder(method))
            methodSource += "\n\n" + CreateForwarder(method);

        return new GeneratedFile(
            $"IfItQuacks.Fallback.{SanitizeHintName(method.ContainingType.ToDisplayString())}.{method.Name}.g.cs",
            Header + TypeWrapper.WrapInContainingScope(method.ContainingType, methodSource));
    }

    // An extension method's first parameter keeps its 'this', so the generated overload can still be called on a receiver.
    private static string DeclareParameter(IMethodSymbol method, IParameterSymbol parameter, string type) =>
        (method.IsExtensionMethod && parameter.Ordinal == 0 ? "this " : "") + Utilities.Parameter(parameter, type);

    private static string CreateFallbackVariant(IMethodSymbol method, ImmutableArray<IParameterSymbol> genericParameters)
    {
        var typeParameterNames = genericParameters.ToDictionary(p => p.Ordinal, FallbackTypeParameterName);

        var parameters = string.Join(", ", method.Parameters.Select(p => typeParameterNames.TryGetValue(p.Ordinal, out var name)
            ? DeclareParameter(method, p, name) + GenericDefaultValue(p)
            : DeclareParameter(method, p, p.Type.ToDisplayString()) + Utilities.DefaultValue(p)));
        // Calls that couldn't be verified at compile time (e.g. from generic code) still work if the value implements the interface at runtime.
        var arguments = string.Join(", ", method.Parameters.Select(p => typeParameterNames.TryGetValue(p.Ordinal, out var name)
            ? RuntimeCast(p, name)
            : Utilities.Argument(p)));

        return $$"""
            {{EditorBrowsableNever}}
            {{Utilities.AccessibilityKeyword(method.DeclaredAccessibility)}} {{(method.IsStatic ? "static " : "")}}{{method.ReturnType.ToDisplayString()}} {{method.Name}}<{{string.Join(", ", typeParameterNames.Values)}}>({{parameters}})
            {
                {{(method.ReturnsVoid ? "" : "return ")}}{{method.Name}}({{arguments}});
            }
            """;
    }

    // Interceptors live in their own namespace, so methods they can't access are called through an internal forwarder on the containing type.
    private static bool NeedsForwarder(IMethodSymbol method) =>
        method.DeclaredAccessibility is Accessibility.Private or Accessibility.Protected or Accessibility.ProtectedAndInternal;

    private static string ForwarderName(IMethodSymbol method) => $"__IfItQuacks_{method.Name}";

    private static string CreateForwarder(IMethodSymbol method)
    {
        var parameters = string.Join(", ", method.Parameters.Select(p => Utilities.Parameter(p, p.Type.ToDisplayString())));
        var arguments = string.Join(", ", method.Parameters.Select(Utilities.Argument));
        var modifiers = (method.IsStatic ? "static " : "") + (method.IsReadOnly ? "readonly " : "");
        return $"{EditorBrowsableNever}\n" +
               $"internal {modifiers}{method.ReturnType.ToDisplayString()} {ForwarderName(method)}({parameters}) => {method.Name}({arguments});";
    }

    // Interceptors must keep the intercepted signature, so a generic fallback can't return the per-call inferred type; concrete overloads can.
    private static OverloadMember CreateDuckOverload(IMethodSymbol method, IMethodSymbol constructed,
        Dictionary<int, (ITypeSymbol ConcreteType, string? AdapterName)> duckArguments)
    {
        var accessibility = OverloadAccessibility(method, duckArguments.Values.Select(a => a.ConcreteType));

        var parameters = string.Join(", ", constructed.Parameters.Select(p =>
            DeclareParameter(method, p, duckArguments.TryGetValue(p.Ordinal, out var duck) ? duck.ConcreteType.ToDisplayString() : p.Type.ToDisplayString()) +
            Utilities.DefaultValue(p)));

        var arguments = string.Join(", ", constructed.Parameters.Select(p =>
            duckArguments.TryGetValue(p.Ordinal, out var duck) && duck.AdapterName is not null
                ? $"new global::{GeneratedNamespace}.{duck.AdapterName}({Utilities.Identifier(p.Name)})"
                : Utilities.Argument(p)));

        var typeArguments = constructed.TypeArguments.IsEmpty
            ? ""
            : $"<{string.Join(", ", constructed.TypeArguments.Select(t => t.ToDisplayString()))}>";
        var member =
            $"{EditorBrowsableNever} {accessibility} {(method.IsStatic ? "static " : "")}{constructed.ReturnType.ToDisplayString()} {method.Name}({parameters}) => " +
            $"{method.Name}{typeArguments}({arguments});";

        return CreateOverloadMember(method, member);
    }

    // A public overload can't expose a non-public argument type, so it falls back to internal.
    private static string OverloadAccessibility(IMethodSymbol method, IEnumerable<ITypeSymbol> concreteTypes) =>
        method.DeclaredAccessibility is Accessibility.Public or Accessibility.Protected or Accessibility.ProtectedOrInternal &&
        !concreteTypes.All(IsPubliclyVisible)
            ? "internal"
            : Utilities.AccessibilityKeyword(method.DeclaredAccessibility);

    private static OverloadMember CreateOverloadMember(IMethodSymbol method, string member)
    {
        var (prefix, suffix) = TypeWrapper.WrapTemplate(method.ContainingType);
        return new OverloadMember(
            $"IfItQuacks.Overloads.{SanitizeHintName(method.ContainingType.ToDisplayString())}.{method.Name}.g.cs",
            Header + prefix, suffix, member);
    }

    private static string CreateInterceptor(InterceptableLocation location, IMethodSymbol method,
        Dictionary<int, (ITypeSymbol ConcreteType, string? AdapterName)> duckArguments, bool isReduced)
    {
        // Anonymous types can't be named in the signature, so the interceptor stays generic like the fallback it replaces.
        var isGeneric = duckArguments.Values.Any(d => d.ConcreteType.IsAnonymousType);
        var parameters = method.Parameters.Select(p =>
        {
            // A call on a receiver is intercepted by an extension method, whatever the intercepted method is declared as.
            var thisModifier = isReduced && p.Ordinal == 0 ? "this " : "";
            if (!duckArguments.TryGetValue(p.Ordinal, out var duck))
                return thisModifier + Utilities.Parameter(p, p.Type.ToDisplayString());
            return thisModifier + Utilities.Parameter(p, isGeneric ? FallbackTypeParameterName(p) : duck.ConcreteType.ToDisplayString());
        });
        if (!method.IsStatic)
        {
            // Struct receivers are passed by reference, so mutations made by the method reach the caller's value.
            var receiverRefKind = method.IsReadOnly ? "in " : "ref ";
            parameters = parameters.Prepend($"this {(method.ContainingType.IsValueType ? receiverRefKind : "")}global::{method.ContainingType.ToDisplayString()} @this");
        }

        // Casting to the shape interface makes overload resolution pick the real method instead of the generated generic fallback.
        var arguments = method.Parameters.Select(p =>
        {
            if (!duckArguments.TryGetValue(p.Ordinal, out var duck))
                return Utilities.Argument(p);

            var name = Utilities.Identifier(p.Name);
            if (isGeneric)
                name = duck.ConcreteType.IsAnonymousType ? $"(object){name}!" : $"({duck.ConcreteType.ToDisplayString()})(object){name}!";
            var value = duck.AdapterName is null ? name : $"new global::{GeneratedNamespace}.{duck.AdapterName}({name})";
            return $"(global::{WithoutNullability(p.Type).ToDisplayString()})({value})";
        });
        var typeParameters = isGeneric ? $"<{string.Join(", ", duckArguments.Keys.OrderBy(o => o).Select(o => FallbackTypeParameterName(method.Parameters[o])))}>" : "";

        var receiver = method.IsStatic ? $"global::{method.ContainingType.ToDisplayString()}" : "@this";
        var call = $"{receiver}.{(NeedsForwarder(method) ? ForwarderName(method) : method.Name)}({string.Join(", ", arguments)});";

        var sb = new StringBuilder();
        sb.AppendLine("        " + location.GetInterceptsLocationAttributeSyntax());
        sb.AppendLine($"        public static {method.ReturnType.ToDisplayString()} Interceptor_{InterceptorIndexPlaceholder}{typeParameters}({string.Join(", ", parameters)})");
        sb.AppendLine("        {");
        sb.AppendLine(method.ReturnsVoid ? $"            {call}" : $"            return {call}");
        sb.AppendLine("        }");
        return sb.ToString();
    }

    private static string GenericDefaultValue(IParameterSymbol parameter) => parameter.HasExplicitDefaultValue ? " = default!" : "";

    private static string RuntimeCast(IParameterSymbol parameter, string typeParameterName)
    {
        var identifier = Utilities.Identifier(parameter.Name);
        var interfaceName = $"global::{WithoutNullability(parameter.Type).ToDisplayString()}";
        var allowNull = parameter.Type.NullableAnnotation == NullableAnnotation.Annotated ? $"{identifier} is null ? null : " : "";
        return $"{identifier} is {interfaceName} __duck{parameter.Ordinal} ? __duck{parameter.Ordinal} : {allowNull}" +
               $"throw new global::IfItQuacks.DuckTypeMismatchException(typeof({typeParameterName}), typeof({interfaceName}))";
    }

    private static ITypeSymbol WithoutNullability(ITypeSymbol type) => type.WithNullableAnnotation(NullableAnnotation.NotAnnotated);

    private static string FallbackTypeParameterName(IParameterSymbol parameter) => $"TDuck{parameter.Ordinal}";

    private static string SanitizeHintName(string name) => name.Replace('.', '_').Replace('<', '_').Replace('>', '_').Replace(',', '_').Replace(' ', '_');

    private static bool IsPubliclyVisible(ITypeSymbol type) => type switch
    {
        INamedTypeSymbol named => IsDeclaredPublic(named) && named.TypeArguments.All(IsPubliclyVisible),
        IArrayTypeSymbol array => IsPubliclyVisible(array.ElementType),
        _ => true,
    };

    private static bool IsDeclaredPublic(INamedTypeSymbol type) =>
        Utilities.EnclosingTypes(type).All(t => t.DeclaredAccessibility == Accessibility.Public);

    private static bool ContainsTypeParameter(ITypeSymbol type, ITypeParameterSymbol typeParameter) =>
        Utilities.ContainsType(type, t => SymbolEqualityComparer.Default.Equals(t, typeParameter));

    private static bool ContainsAnyTypeParameter(ITypeSymbol type) =>
        Utilities.ContainsType(type, t => t is ITypeParameterSymbol);
}
