<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />
  <Import Project="$(MSBuildThisFileDirectory)..\build\Consumer.props" />

  <PropertyGroup>
    <ServerGarbageCollection>false</ServerGarbageCollection>
    <!-- BenchmarkDotNet requires public benchmark types and members. -->
    <NoWarn>$(NoWarn);CA1515</NoWarn>
  </PropertyGroup>
</Project>
